CREATE TABLE `report_creative` (
  `date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `accountId` bigint(20) unsigned DEFAULT NULL,
  `profileId` bigint(20) unsigned DEFAULT NULL,
  `campaignId` bigint(20) unsigned DEFAULT NULL,
  `advertiserId` bigint(20) unsigned DEFAULT NULL,
  `placementId` bigint(20) unsigned DEFAULT NULL,
  `creativeId` bigint(20) unsigned DEFAULT NULL,
  `siteId` bigint(20) unsigned DEFAULT NULL,
  `size` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `creativeType` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `adType` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `excludeCode` bigint(20) unsigned DEFAULT NULL,
  `impressions` bigint(20) unsigned DEFAULT NULL,
  `clicks` bigint(20) unsigned DEFAULT NULL,
  `interactiveImp` bigint(20) unsigned DEFAULT NULL,
  `richMediaClicks` bigint(20) unsigned DEFAULT NULL,
  `richMediaImp` bigint(20) unsigned DEFAULT NULL,
  `avgInteractionTime` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `totalInterractionTime` bigint(20) unsigned DEFAULT NULL,
  `totalInterractions` bigint(20) unsigned DEFAULT NULL,
  `totalConversions` bigint(20) unsigned DEFAULT NULL,
  `clickThroughConv` bigint(20) unsigned DEFAULT NULL,
  `viewThroughConv` bigint(20) unsigned DEFAULT NULL,
  `videoFirstQuatileCompletions` bigint(20) unsigned DEFAULT NULL,
  `videoThirdQuatileCompletions` bigint(20) unsigned DEFAULT NULL,
  `videoMidpoints` bigint(20) unsigned DEFAULT NULL,
  `videoCompletions` bigint(20) unsigned DEFAULT NULL,
  `videoPlays` bigint(20) unsigned DEFAULT NULL,
  `videoReplays` bigint(20) unsigned DEFAULT NULL,
  `videoViews` bigint(20) unsigned DEFAULT NULL,
  `videoInteractions` bigint(20) unsigned DEFAULT NULL,
  `expansions` bigint(20) unsigned DEFAULT NULL,
  `avViewableImpressions` bigint(20) unsigned DEFAULT NULL,
  `avMeasurableImpressions` bigint(20) unsigned DEFAULT NULL,
  SHARD KEY `__SHARDKEY` (`creativeId`),
  SORT KEY `creativeId` (`creativeId`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
