CREATE TABLE `ai_asset_builder_campaign_activation_variation_cm` (
  `uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `activationUuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `approvalUuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `placementName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `placementNameParts` json DEFAULT NULL,
  `siteId` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `placementStart` date NOT NULL,
  `placementEnd` date NOT NULL,
  `testingStart` date DEFAULT NULL,
  `adName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `creativeName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'CM creative name built at submit (${theme_name}_${variation}_${placement_size}, or a custom advertiser format)',
  `creativeNameParts` json DEFAULT NULL COMMENT 'Structured creative-naming inputs snapshotted at submit (custom advertisers only).',
  `exitUrl` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL,
  `utm` json DEFAULT NULL,
  `htmlBucket` varchar(63) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `htmlPrefix` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stage` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `retryCount` int(10) unsigned NOT NULL DEFAULT '0',
  `nextAttemptAt` datetime DEFAULT NULL,
  `cmCreativeId` bigint(20) unsigned DEFAULT NULL,
  `cmDefaultCreativeId` bigint(20) unsigned DEFAULT NULL,
  `cmPlacementId` bigint(20) unsigned DEFAULT NULL,
  `cmAdId` bigint(20) unsigned DEFAULT NULL,
  `error` text COLLATE utf8mb4_unicode_ci,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime DEFAULT NULL,
  `content` json DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  KEY `idx_avcm_activation` (`activationUuid`),
  KEY `idx_avcm_approval` (`approvalUuid`),
  KEY `idx_avcm_status_retry` (`status`,`nextAttemptAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
