CREATE TABLE `ai_asset_builder_campaign_approval_variation` (
  `uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `approvalUuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaignUuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `variationUuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `templateUnitUuid` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` json NOT NULL,
  `templateThemeUnitUuid` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `templateAdjustment` json NOT NULL,
  `htmlBucket` varchar(63) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `htmlPrefix` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `width` int(10) unsigned DEFAULT NULL,
  `height` int(10) unsigned DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `requestedBy` int(10) unsigned DEFAULT NULL,
  `approvedBy` int(10) unsigned DEFAULT NULL,
  `decidedLockUuid` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `note` text COLLATE utf8mb4_unicode_ci,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime DEFAULT NULL,
  `requestedAt` datetime DEFAULT NULL,
  `approvedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `uq_apv_approval_unit` (`approvalUuid`,`variationUuid`,`templateThemeUnitUuid`),
  KEY `idx_apv_campaign` (`campaignUuid`),
  KEY `idx_apv_variation` (`variationUuid`),
  KEY `idx_apv_themeunit` (`templateThemeUnitUuid`),
  KEY `idx_apv_status` (`status`),
  KEY `idx_apv_approval` (`approvalUuid`),
  KEY `idx_apv_templateunit` (`templateUnitUuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
