CREATE TABLE `ai_asset_builder_campaign_variation` (
  `uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Variation UUID',
  `narrativeUuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ref: campaign_narrative.uuid',
  `campaignUuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ref: campaign.uuid (denormalized for querying)',
  `channel` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'display/search/social/email',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Short LLM-authored variation label, slugged + deduped within the campaign; feeds the ${variation} element of the creative name',
  `schemaHash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SHA-256 hash of the template schema this variation targets — one variation covers all templates with matching (clientUuid, schemaHash) for the same narrative/channel/language (ADR-028).',
  `templateId` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Optional per-template override (ADR-028). When set, resolver prefers exact templateId match over schemaHash match. TODO: drop this column if the override feature is never adopted.',
  `language` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'en' COMMENT 'Language code (validated against di_api.language)',
  `variationNumber` int(11) NOT NULL COMMENT 'Position in generation batch (1, 2, 3)',
  `content` json DEFAULT NULL COMMENT 'Channel-specific ad copy fields (JSON, editable)',
  `originalContent` json DEFAULT NULL COMMENT 'Original AI-generated content (immutable, for reset)',
  `generationParams` json DEFAULT NULL COMMENT 'AI generation settings (temperature, writingStyleParams)',
  `modelUuid` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'LLM model reference',
  `userFeedback` text COLLATE utf8mb4_unicode_ci COMMENT 'User feedback for regeneration',
  `isSelected` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Selected for campaign export',
  `generatedFor` int(11) NOT NULL COMMENT 'User ID who triggered generation',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  KEY `idx_narrative_uuid` (`narrativeUuid`),
  KEY `idx_campaign_uuid` (`campaignUuid`),
  KEY `idx_campaign_channel` (`campaignUuid`,`channel`),
  KEY `idx_campaign_channel_selected` (`campaignUuid`,`channel`,`isSelected`),
  KEY `idx_narrative_channel_schema` (`narrativeUuid`,`channel`,`language`,`schemaHash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI-generated ad copy variations per narrative/channel/template';
