CREATE TABLE `alphix_custom_report` (
  `uuid` varchar(36) NOT NULL,
  `clientUuid` varchar(36) NOT NULL,
  `type` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `creator` int(10) NOT NULL,
  `accessLevel` varchar(20) NOT NULL,
  `alphixCustomReportFolderUuid` varchar(36) DEFAULT NULL,
  `lastRun` datetime DEFAULT NULL,
  `nextRun` datetime DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'live',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  KEY `idx_clientUuid` (`clientUuid`),
  KEY `idx_type` (`type`),
  KEY `idx_name` (`name`),
  KEY `idx_creator` (`creator`),
  KEY `idx_accessLevel` (`accessLevel`),
  KEY `idx_alphixCustomReportFolderUuid` (`alphixCustomReportFolderUuid`),
  KEY `idx_nextRun` (`nextRun`),
  KEY `idx_createdAt` (`createdAt`),
  KEY `idx_updatedAt` (`updatedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
