CREATE TABLE `di_ca_placements` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `bookingUniqueNumber` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `placementId` bigint(20) unsigned NOT NULL,
  `userId` int(11) DEFAULT NULL,
  `tsfUuid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `reportImpressions` int(11) DEFAULT NULL,
  `reportClicks` int(11) DEFAULT NULL,
  `reportConversions` int(11) DEFAULT NULL,
  `cpm` decimal(15,4) DEFAULT NULL,
  `cpc` decimal(15,4) DEFAULT NULL,
  `type` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `bookingDateStart` date DEFAULT NULL,
  `bookingDateEnd` date DEFAULT NULL,
  `cost` decimal(15,4) DEFAULT NULL,
  `syncedBooking` tinyint(4) DEFAULT NULL,
  `currency` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `booked_impressions` int(11) DEFAULT NULL,
  `calc_cpm` decimal(15,4) DEFAULT NULL,
  `placementRatio` decimal(15,10) NOT NULL,
  `trafficDays` int(10) unsigned NOT NULL,
  `reportVideo` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `placementBooking` (`placementId`,`bookingUniqueNumber`),
  KEY `uniqueBookingPlacement` (`bookingUniqueNumber`,`placementId`),
  KEY `userId` (`userId`),
  KEY `placementId` (`placementId`),
  KEY `type` (`type`),
  KEY `bookingUniqueNumber` (`bookingUniqueNumber`),
  KEY `reportImpressions` (`reportImpressions`),
  KEY `reportClicks` (`reportClicks`)
) ENGINE=InnoDB AUTO_INCREMENT=824659 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
