CREATE TABLE `firmo_master` (
  `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `firmoIndustryClassificationUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firmoIndustryUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firmoSizeUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firmoTurnoverUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firmoHeadOfficeUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `aicsSubIndustryCode` int(10) unsigned DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `website` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeBand` varchar(50) DEFAULT NULL,
  `turnoverAmount` decimal(25,5) DEFAULT NULL,
  `turnoverBand` varchar(50) DEFAULT NULL,
  `turnoverAmountCurrency` varchar(10) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  PRIMARY KEY (`uuid`),
  KEY `firmo_master_firmoIndustryClassificationUuid_IDX` (`firmoIndustryClassificationUuid`) USING BTREE,
  KEY `firmo_master_firmoIndustryUuid_IDX` (`firmoIndustryUuid`) USING BTREE,
  KEY `firmo_master_firmoSizeUuid_IDX` (`firmoSizeUuid`) USING BTREE,
  KEY `firmo_master_firmoTurnoverUuid_IDX` (`firmoTurnoverUuid`) USING BTREE,
  KEY `firmo_master_firmoHeadOfficeUuid_IDX` (`firmoHeadOfficeUuid`) USING BTREE,
  KEY `firmo_master_createdAt_IDX` (`createdAt`) USING BTREE,
  KEY `name` (`name`),
  KEY `uuid_name` (`uuid`,`name`),
  KEY `idx_website` (`website`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
