CREATE TABLE `persona` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `creator` int(10) unsigned NOT NULL,
  `clientUuid` varchar(36) DEFAULT NULL,
  `accessLevel` varchar(32) NOT NULL,
  `datasetId` int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `filter` json NOT NULL,
  `respondentCount` int(10) unsigned NOT NULL,
  `fieldData` json NOT NULL,
  `aiHeadline` varchar(255) NOT NULL,
  `aiDetails` text NOT NULL,
  `aiCategorySummaries` json DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `activationBrief` json DEFAULT NULL,
  `competitiveAnalysis` json DEFAULT NULL,
  `undercurrents` json DEFAULT NULL,
  `productSignals` json DEFAULT NULL,
  `personaSummary` json DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=153 DEFAULT CHARSET=utf8mb4;
