CREATE TABLE `psychographix_personas` (
  `persona_id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `persona_title` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `persona_description` text COLLATE utf8mb4_unicode_ci,
  `scope` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'individual',
  `concerns` text COLLATE utf8mb4_unicode_ci,
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `client_uuid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `investing_knowledge` tinyint(4) DEFAULT NULL,
  `investing_involvement` tinyint(4) DEFAULT NULL,
  `risk_tolerance` tinyint(4) DEFAULT NULL,
  `reliance_on_experts` tinyint(4) DEFAULT NULL,
  `investing_enjoyment` tinyint(4) DEFAULT NULL,
  `financial_comfort` tinyint(4) DEFAULT NULL,
  `analytical_approach` tinyint(4) DEFAULT NULL,
  `passives_vs_active` tinyint(4) DEFAULT NULL,
  `investment_horizon` tinyint(4) DEFAULT NULL,
  `liquidity_preference` tinyint(4) DEFAULT NULL,
  `asset_class_affinity` tinyint(4) DEFAULT NULL,
  `wealth_orientation` tinyint(4) DEFAULT NULL,
  `innovation_adoption` tinyint(4) DEFAULT NULL,
  `decision_speed` tinyint(4) DEFAULT NULL,
  `community_orientation` tinyint(4) DEFAULT NULL,
  `custom_scores` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `archived_at` datetime DEFAULT NULL,
  PRIMARY KEY (`persona_id`),
  KEY `idx_created_by` (`created_by`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
