CREATE TABLE `psychographix_funds` (
  `fund_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fund_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ticker` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `branding_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_uuid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `investment_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `global_broad_category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `global_category` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isin` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source` tinytext COLLATE utf8mb4_unicode_ci,
  `scope` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'private',
  `currency` char(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fund_size_aum` decimal(20,2) DEFAULT NULL,
  `sharpe_ratio_1y` decimal(8,4) DEFAULT NULL,
  `sharpe_ratio_3y` decimal(8,4) DEFAULT NULL,
  `sharpe_ratio_5y` decimal(8,4) DEFAULT NULL,
  `return_1y` decimal(8,4) DEFAULT NULL,
  `return_3y` decimal(8,4) DEFAULT NULL,
  `return_5y` decimal(8,4) DEFAULT NULL,
  `management_fee` decimal(6,4) DEFAULT NULL,
  `inception_date` date DEFAULT NULL,
  `yield_12m` decimal(7,4) DEFAULT NULL,
  `fund_objective` text COLLATE utf8mb4_unicode_ci,
  `shares_outstanding` bigint(20) unsigned DEFAULT NULL,
  `beta` decimal(7,4) DEFAULT NULL,
  `stability_score` tinyint(4) DEFAULT NULL,
  `volatility_score` tinyint(4) DEFAULT NULL,
  `growth_tilt_score` tinyint(4) DEFAULT NULL,
  `income_score` tinyint(4) DEFAULT NULL,
  `diversification_score` tinyint(4) DEFAULT NULL,
  `liquidity_score` tinyint(4) DEFAULT NULL,
  `complexity_score` tinyint(4) DEFAULT NULL,
  `historical_resilience_score` tinyint(4) DEFAULT NULL,
  `innovation_score` tinyint(4) DEFAULT NULL,
  `trust_brand_score` tinyint(4) DEFAULT NULL,
  `custom_attrs` json DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `archived_at` datetime DEFAULT NULL,
  PRIMARY KEY (`fund_uuid`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_ticker` (`ticker`),
  KEY `idx_branding_name` (`branding_name`),
  KEY `idx_client_uuid` (`client_uuid`),
  KEY `idx_investment_type` (`investment_type`),
  KEY `idx_broad_category` (`global_broad_category`),
  KEY `idx_currency` (`currency`),
  KEY `idx_inception_date` (`inception_date`),
  KEY `idx_fund_id` (`fund_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
