CREATE TABLE `targeting_profile_content` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `description` mediumtext COLLATE utf8_unicode_ci,
  `creator` int(10) unsigned DEFAULT NULL,
  `status` tinyint(4) DEFAULT '1',
  `sentiment_negative` tinyint(4) NOT NULL DEFAULT '0',
  `sentiment_neutral` tinyint(4) NOT NULL DEFAULT '0',
  `sentiment_positive` tinyint(4) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `updatedAt` datetime DEFAULT NULL,
  `clientUuid` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `startDate` datetime DEFAULT NULL,
  `similarityScore` decimal(10,8) DEFAULT NULL,
  `terms` varchar(20000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `domainList` mediumtext COLLATE utf8_unicode_ci,
  `language` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `include` mediumtext COLLATE utf8_unicode_ci,
  `exclude` mediumtext COLLATE utf8_unicode_ci,
  `segmentKey` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `slowSearch` tinyint(4) DEFAULT '1',
  `version` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`),
  KEY `sentiment_negative` (`sentiment_negative`),
  KEY `sentiment_neutral` (`sentiment_neutral`),
  KEY `sentiment_positive` (`sentiment_positive`),
  KEY `clientUuid` (`clientUuid`)
) ENGINE=InnoDB AUTO_INCREMENT=1207 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
