CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `verified` int(11) NOT NULL,
  `verification_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `status` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `locale` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `client_access_all` tinyint(4) NOT NULL,
  `twoFAstatus` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'disabled',
  `twoFAsecretOTP` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `emailSecurityCode` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `emailOptOutStatus` tinyint(1) DEFAULT '0',
  `lastPasswordReset` date DEFAULT NULL,
  `forcePasswordReset` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `MSApproved` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `lastPasswordReset` (`lastPasswordReset`)
) ENGINE=InnoDB AUTO_INCREMENT=1538 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
