CREATE TABLE `vector_ad` (
  `uuid` varchar(36) NOT NULL,
  `vectorPageUuid` varchar(36) DEFAULT NULL,
  `vectorNewsUuid` varchar(36) DEFAULT NULL,
  `contentVersion` int(11) DEFAULT '1',
  `name` varchar(200) DEFAULT NULL,
  `description` text,
  `type` varchar(50) DEFAULT NULL,
  `language` varchar(10) DEFAULT 'en',
  `status` varchar(20) DEFAULT NULL,
  `prompt` text,
  `settings` mediumtext,
  `properties` text,
  `archived` tinyint(1) NOT NULL DEFAULT '0',
  `creator` int(11) DEFAULT NULL,
  `alphixTopicUuid` varchar(36) DEFAULT NULL,
  `trendsBoardUuid` varchar(36) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `updatedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  KEY `vectorPageUuid` (`vectorPageUuid`) USING BTREE,
  KEY `vectorNewsUuid` (`vectorNewsUuid`) USING BTREE,
  KEY `status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
