CREATE TABLE `hits_country_weekly_copy` (
  `date` date NOT NULL DEFAULT '0000-00-00 00:00:00',
  `clientUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `url_clean_id` int(11) NOT NULL DEFAULT '0',
  `country` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `domain_id` int(11) DEFAULT NULL,
  `sectorCode` int(11) DEFAULT NULL,
  `industryGroupCode` int(11) DEFAULT NULL,
  `industryCode` int(11) DEFAULT NULL,
  `subIndustryCode` int(11) DEFAULT NULL,
  `hits` bigint(20) DEFAULT NULL,
  `botHits` bigint(20) DEFAULT NULL,
  `commercialHits` bigint(20) DEFAULT NULL,
  `organicHits` bigint(20) DEFAULT NULL,
  `urlHits` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`url_clean_id`,`date`,`clientUuid`,`country`),
  SHARD KEY `__SHARDKEY` (`url_clean_id`,`date`,`clientUuid`),
  SORT KEY `date` (`date`,`clientUuid`,`country`),
  KEY `date_idx` (`date`) USING HASH,
  KEY `client_idx` (`clientUuid`) USING HASH,
  KEY `url_idx` (`url_clean_id`) USING HASH,
  KEY `country_idx` (`country`) USING HASH,
  KEY `domain_idx` (`domain_id`) USING HASH,
  KEY `gics_idx` (`sectorCode`,`industryGroupCode`,`industryCode`,`subIndustryCode`) USING HASH,
  KEY `clientUuid` (`clientUuid`,`country`,`date`) USING HASH
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
