CREATE TABLE `opportunity_score` (
  `topicUuidCountry` varchar(46) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `clientUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `date` date NOT NULL,
  `topicUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `country` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `summary` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `currentOpportunityScore` decimal(5,2) NOT NULL,
  `currentMarketSize` decimal(5,2) NOT NULL,
  `currentBrandPresence` decimal(5,2) NOT NULL,
  `currentGrowth` decimal(5,2) NOT NULL,
  `currentGap` decimal(5,2) NOT NULL,
  `currentWhiteSpace` decimal(5,2) NOT NULL,
  `currentSpend4Week` decimal(12,2) NOT NULL,
  `currentScenario` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `previousOpportunityScore` decimal(5,2) NOT NULL,
  `previousMarketSize` decimal(5,2) NOT NULL,
  `previousBrandPresence` decimal(5,2) NOT NULL,
  `previousGrowth` decimal(5,2) NOT NULL,
  `previousGap` decimal(5,2) NOT NULL,
  `previousWhiteSpace` decimal(5,2) NOT NULL,
  `previousSpend4Week` decimal(12,2) NOT NULL,
  `previousScenario` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `growthClientWeek1` decimal(7,2) NOT NULL,
  `growthClientWeek4` decimal(7,2) NOT NULL,
  `growthClientWeek12` decimal(7,2) NOT NULL,
  `growthClientWeighted` decimal(7,2) NOT NULL,
  `growthCompetitorWeek1` decimal(7,2) NOT NULL,
  `growthCompetitorWeek4` decimal(7,2) NOT NULL,
  `growthCompetitorWeek12` decimal(7,2) NOT NULL,
  `growthCompetitorWeighted` decimal(7,2) NOT NULL,
  `growthMarketWeek1` decimal(7,2) NOT NULL,
  `growthMarketWeek4` decimal(7,2) NOT NULL,
  `growthMarketWeek12` decimal(7,2) NOT NULL,
  `growthMarketWeighted` decimal(7,2) NOT NULL,
  `debug` JSON COLLATE utf8mb4_bin,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `currentSpend12Week` decimal(12,2) NOT NULL,
  `previousSpend12Week` decimal(12,2) NOT NULL,
  `growthClientTrend` JSON COLLATE utf8mb4_bin,
  `growthCompetitorTrend` JSON COLLATE utf8mb4_bin,
  `growthMarketTrend` JSON COLLATE utf8mb4_bin,
  PRIMARY KEY (`topicUuidCountry`,`clientUuid`,`date`),
  SHARD KEY `__SHARDKEY` (`topicUuidCountry`,`clientUuid`,`date`),
  KEY `topicUuidCountry` (`topicUuidCountry`) USING HASH,
  KEY `clientUuid` (`clientUuid`) USING HASH,
  KEY `topicUuid` (`topicUuid`) USING HASH,
  KEY `country` (`country`) USING HASH,
  KEY `date` (`date`) USING HASH,
  SORT KEY `__UNORDERED` ()
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
