CREATE TABLE `page_log_B1C85EB4_FEC5_5541_9C6E_F28D0D1B2C7A` (
  `alphix_ledger` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `amx_line_item_id` bigint(20) unsigned DEFAULT NULL,
  `amx_auction_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `booking_creative_id` bigint(20) unsigned DEFAULT NULL,
  `booking_line_item_id` bigint(20) unsigned DEFAULT NULL,
  `booking_placement_id` bigint(20) unsigned DEFAULT NULL,
  `booking_unique_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `code_version` decimal(10,4) DEFAULT NULL,
  `country` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `delta_tag` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `delta_tag_unique` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `delta_tag_unique_duplicate` tinyint(4) DEFAULT NULL,
  `domain_id` int(10) unsigned DEFAULT NULL,
  `dt_client_uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `dynamic_unique_number` bigint(20) unsigned DEFAULT NULL,
  `facebook_ad_id` bigint(20) unsigned DEFAULT NULL,
  `google_ads_ad_group_id` bigint(20) unsigned DEFAULT NULL,
  `google_ads_ad_id` bigint(20) unsigned DEFAULT NULL,
  `google_ads_keyword` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `google_ads_placement_category_id` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `ip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `linkedin_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `linkedin_creative_id` bigint(20) unsigned DEFAULT NULL,
  `page` varchar(21843) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `path` varchar(21843) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `random` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `referer` varchar(8192) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `smart_placement_stream_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `timestamp` datetime NOT NULL,
  `timestampDate` date NOT NULL,
  `firmoMasterUuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `twitter_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `ua` varchar(8192) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `url_clean` varchar(8192) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `url_clean_id` int(10) unsigned DEFAULT NULL,
  `dimension` JSON COLLATE utf8mb4_bin,
  `isBot` tinyint(1) DEFAULT NULL,
  `time_bucket` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `booking_site_id` bigint(20) unsigned DEFAULT NULL,
  `paid_media_site` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `time_on_page` bigint(30) unsigned DEFAULT NULL,
  `browser` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `device` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `hardwareType` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `os` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `simpleSoftwareString` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `softwareType` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `botType` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `sessionId` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `firstVisit` tinyint(1) DEFAULT 1,
  `lastVisit` tinyint(1) DEFAULT 1,
  `sessionPageViews` int(20) unsigned DEFAULT NULL,
  `sessionTotalTime` decimal(18,3) unsigned DEFAULT NULL,
  `filter_list_uuid` JSON COLLATE utf8mb4_bin DEFAULT NULL,
  `clientAdditional` JSON COLLATE utf8mb4_bin DEFAULT NULL,
  `session_path_list` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `session_url_clean_id_list` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  SHARD KEY `__SHARDKEY` (`domain_id`,`path`,`id`),
  UNIQUE KEY `PRIMARY` (`domain_id`,`path`,`id`) USING HASH,
  SORT KEY `__UNORDERED` ()
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
