CREATE TABLE `page_log_156316B4_FA0F_3A4A_B885_DE3E674A5872` (
  `domain_id` int(10) unsigned DEFAULT NULL,
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `path` varchar(21843) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `alphix_ledger` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `amx_line_item_id` bigint(20) unsigned DEFAULT NULL,
  `amx_auction_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `booking_creative_id` bigint(20) unsigned DEFAULT NULL,
  `booking_line_item_id` bigint(20) unsigned DEFAULT NULL,
  `booking_placement_id` bigint(20) unsigned DEFAULT NULL,
  `booking_unique_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `code_version` decimal(10,4) DEFAULT NULL,
  `country` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `dynamic_unique_number` bigint(20) unsigned DEFAULT NULL,
  `facebook_ad_id` bigint(20) unsigned DEFAULT NULL,
  `google_ads_ad_group_id` bigint(20) unsigned DEFAULT NULL,
  `google_ads_ad_id` bigint(20) unsigned DEFAULT NULL,
  `google_ads_keyword` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `google_ads_placement_category_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `linkedin_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `linkedin_creative_id` bigint(20) unsigned DEFAULT NULL,
  `smart_placement_stream_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `twitter_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `dt_client_uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `page` varchar(21843) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `random` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `referer` varchar(8192) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `timestamp` datetime NOT NULL,
  `timestampDate` date NOT NULL,
  `firmoMasterUuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `browser` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `device` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `hardwareType` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `os` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `simpleSoftwareString` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `softwareType` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ua` varchar(8192) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `url_clean` varchar(8192) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `url_clean_id` int(10) unsigned DEFAULT NULL,
  `dimension` JSON COLLATE utf8mb4_bin,
  `isBot` tinyint(1) DEFAULT NULL,
  `botType` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `sessionId` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ip_list` JSON COLLATE utf8mb4_bin DEFAULT NULL,
  `filter_list_uuid` JSON COLLATE utf8mb4_bin DEFAULT NULL,
  SHARD KEY `__SHARDKEY` (`domain_id`,`path`,`id`),
  UNIQUE KEY `PRIMARY` (`domain_id`,`path`,`id`) USING HASH,
  SORT KEY `__UNORDERED` ()
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
