CREATE TABLE `media_custom_report` (
  `date` date NOT NULL,
  `url_hash` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `cm_placment_id` bigint(20) NOT NULL,
  `cm_creative_id` bigint(20) NOT NULL,
  `google_ads_ad_id` bigint(20) NOT NULL,
  `linkedin_creative_id` bigint(20) NOT NULL,
  `facebook_ad_id` bigint(20) NOT NULL,
  `dynamic_unique_number` bigint(20) NOT NULL,
  `url_no_unique` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `url_clean_id` bigint(20) NOT NULL,
  `entrances` int(10) NOT NULL DEFAULT '0',
  `conversions` int(10) NOT NULL DEFAULT '0',
  `duplicateEntrances` int(10) NOT NULL DEFAULT '0',
  `duplicateEntrancesUnique` int(10) NOT NULL DEFAULT '0',
  `bounceEntrances` int(10) NOT NULL DEFAULT '0',
  `bounces` int(10) NOT NULL DEFAULT '0',
  `sessions` int(10) NOT NULL DEFAULT '0',
  `humanDirectEntrance` int(10) NOT NULL DEFAULT '0',
  `humanDirectBounce` int(10) NOT NULL DEFAULT '0',
  `humanPostClickEntrance` int(10) NOT NULL DEFAULT '0',
  `humanPostClickBounce` int(10) NOT NULL DEFAULT '0',
  `botDirectEntrance` int(10) NOT NULL DEFAULT '0',
  `botDirectBounce` int(10) NOT NULL DEFAULT '0',
  `botPostClickEntrance` int(10) NOT NULL DEFAULT '0',
  `botPostClickBounce` int(10) NOT NULL DEFAULT '0',
  `alphixEngaged` int(10) NOT NULL DEFAULT '0',
  `alphixUnengaged` int(10) NOT NULL DEFAULT '0',
  `timeOnPageView` int(10) NOT NULL DEFAULT '0',
  `timeOnPageSecond` decimal(20,5) NOT NULL DEFAULT '0',
  PRIMARY KEY (`url_hash`,`cm_placment_id`,`cm_creative_id`,`google_ads_ad_id`,`linkedin_creative_id`,`facebook_ad_id`,`date`),
  KEY `cm_placment_id` (`cm_placment_id`) USING HASH,
  KEY `cm_creative_id` (`cm_creative_id`) USING HASH,
  KEY `google_ads_ad_id` (`google_ads_ad_id`) USING HASH,
  KEY `linkedin_creative_id` (`linkedin_creative_id`) USING HASH,
  KEY `facebook_ad_id` (`facebook_ad_id`) USING HASH,
  KEY `date` (`date`) USING HASH,
  SHARD KEY `__SHARDKEY` (`url_hash`,`cm_placment_id`,`cm_creative_id`,`google_ads_ad_id`,`linkedin_creative_id`,`facebook_ad_id`,`date`),
  SORT KEY `__UNORDERED` ()
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
