CREATE TABLE `domain` (
  `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `clientUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `domainId` int(10) unsigned NOT NULL,
  `yearMonth` date NOT NULL,
  `llmoScoreAccessible` int(10) unsigned DEFAULT NULL,
  `llmoScoreClear` int(10) unsigned DEFAULT NULL,
  `llmoScoreAuthority` int(10) unsigned DEFAULT NULL,
  `llmoScoreTimeless` int(10) unsigned DEFAULT NULL,
  `llmoScoreOverall` int(10) unsigned DEFAULT NULL,
  `brandAuthority` int(10) unsigned DEFAULT NULL,
  `domainAuthority` int(10) unsigned DEFAULT NULL,
  `backlinks` int(10) unsigned DEFAULT NULL,
  `avgKeywordRanking` decimal(10,2) DEFAULT NULL,
  `pagesProcessed` int(10) unsigned NOT NULL,
  `robotsTxtPresent` tinyint(1) unsigned DEFAULT NULL,
  `llmsTxtPresent` tinyint(1) unsigned DEFAULT NULL,
  `topicsVariety` decimal(10,9) DEFAULT NULL,
  `topicsDispersion` decimal(10,9) DEFAULT NULL,
  `recommendationStoragePath` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime DEFAULT NULL,
  SHARD KEY `__SHARDKEY` (`uuid`),
  UNIQUE KEY `PRIMARY` (`uuid`) USING HASH,
  SORT KEY `__UNORDERED` ()
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
