CREATE TABLE `page` (
  `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `processedAt` datetime NOT NULL,
  `yearMonth` date DEFAULT NULL,
  `domainId` int(10) unsigned NOT NULL,
  `clientUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `urlCleanId` int(10) unsigned NOT NULL,
  `contentStoragePath` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `noTitleInMetadata` tinyint(1) unsigned DEFAULT NULL,
  `noDescriptionInMetadata` tinyint(1) unsigned DEFAULT NULL,
  `noAuthorInMetadata` tinyint(1) unsigned DEFAULT NULL,
  `noPublishedDateInMetadata` tinyint(1) unsigned DEFAULT NULL,
  `noStructuredJsonInMetadata` tinyint(1) unsigned DEFAULT NULL,
  `noLanguageInMetadata` tinyint(1) unsigned DEFAULT NULL,
  `tooLittleMachineReadableText` tinyint(1) unsigned DEFAULT NULL,
  `urlIsRedirect` tinyint(1) unsigned DEFAULT NULL,
  `statusCode` mediumint(3) unsigned NOT NULL,
  `title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `author` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `published_on` date DEFAULT NULL,
  `geography` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `language` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `lexicalDensity` decimal(10,9) DEFAULT NULL,
  `lexicalDiversity` decimal(10,9) DEFAULT NULL,
  `sentimentNegative` decimal(10,9) DEFAULT NULL,
  `sentimentNeutral` decimal(10,9) DEFAULT NULL,
  `sentimentPositive` decimal(10,9) DEFAULT NULL,
  `voiceActive` decimal(10,9) DEFAULT NULL,
  `subjectivityScore` decimal(10,9) DEFAULT NULL,
  `lengthOfText` int(10) unsigned DEFAULT NULL,
  `lengthOfTextNotDisclaimer` int(10) unsigned DEFAULT NULL,
  `medianLoadTimeMs` int(10) unsigned DEFAULT NULL,
  `pageViews` int(10) unsigned DEFAULT NULL,
  `answerEngineViews` int(10) unsigned DEFAULT NULL,
  `ceEligible` tinyint(1) unsigned DEFAULT NULL,
  `isFundFactsheet` tinyint(1) unsigned DEFAULT NULL,
  `ticker` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ISIN` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `assetClass` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `product` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  SHARD KEY `__SHARDKEY` (`uuid`),
  UNIQUE KEY `PRIMARY` (`uuid`) USING HASH,
  SORT KEY `__UNORDERED` ()
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
