CREATE TABLE `advert` (
  `id` bigint(11) unsigned NOT NULL,
  `domain_id` int(11) unsigned DEFAULT NULL,
  `advertiser_id` int(11) unsigned DEFAULT NULL,
  `landing_id` int(11) unsigned DEFAULT NULL,
  `ad_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `timestamp` timestamp NULL DEFAULT NULL,
  `width` int(6) unsigned DEFAULT NULL,
  `height` int(6) unsigned DEFAULT NULL,
  `domain` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `src` varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `finfo` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `server` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `landing` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `landing_strip` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ad_type` tinyint(1) unsigned DEFAULT NULL COMMENT 'adverts_type.id' ,
  `btype_id` int(11) NOT NULL DEFAULT '0',
  `a_id` int(11) NOT NULL DEFAULT '0',
  `strategy_id` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `product_id` int(11) unsigned NOT NULL DEFAULT '0',
  `asset_id` int(11) unsigned NOT NULL DEFAULT '0',
  `last_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` tinyint(4) NOT NULL DEFAULT '0',
  `iframe` tinyint(1) DEFAULT NULL,
  `net_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `cmp_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `pla_id` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `svr_src` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `adv_id` int(11) DEFAULT NULL,
  `x` smallint(6) DEFAULT NULL,
  `y` smallint(6) DEFAULT NULL,
  `utm_source` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `utm_medium` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `utm_campaign` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `keywords` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `keywordsID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0',
  `ignore` tinyint(1) NOT NULL DEFAULT '0',
  `classifyKeywordStatus` int(1) NOT NULL DEFAULT '0',
  `timestamp1` datetime DEFAULT NULL,
  `temp` int(1) NOT NULL DEFAULT '0',
  `country` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `confirmed` tinyint(1) DEFAULT '0' COMMENT '1 - confirmed' ,
  `weight` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'merged duplicated adverts' ,
  `landing_method` smallint(5) unsigned DEFAULT '0' COMMENT 'Landing extraction method' ,
  `hunter_version` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0',
  `storageLocation` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tagName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `metadata` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ad_uid` (`ad_uid`) USING HASH,
  KEY `domain` (`domain`) USING HASH,
  KEY `landing` (`landing`) USING HASH,
  KEY `state` (`state`) USING HASH,
  KEY `landing_strip` (`landing_strip`) USING HASH,
  KEY `timestamp` (`timestamp`) USING HASH,
  KEY `dimensions` (`width`,`height`) USING HASH,
  KEY `country` (`country`) USING HASH,
  KEY `ignore` (`ignore`) USING HASH,
  KEY `product_id` (`product_id`) USING HASH,
  KEY `strategy_id` (`strategy_id`) USING HASH,
  KEY `asset_id` (`asset_id`) USING HASH,
  KEY `ad_type` (`ad_type`) USING HASH,
  KEY `width` (`width`) USING HASH,
  KEY `height` (`height`) USING HASH,
  KEY `src` (`src`) USING HASH,
  KEY `domain_id_fk__adverts` (`domain_id`) USING HASH,
  KEY `advertiser_id_fk__adverts` (`advertiser_id`) USING HASH,
  KEY `weight` (`weight`) USING HASH,
  KEY `landing_id_fk__landings` (`landing_id`) USING HASH,
  SHARD KEY `__SHARDKEY` (`id`),
  SORT KEY `__UNORDERED` (),
  FULLTEXT USING VERSION 1 KEY `advert_metadata_IDX` (`metadata`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
