CREATE TABLE `impression` (
  `id` int(11) NOT NULL,
  `advert_id` int(11) unsigned DEFAULT NULL,
  `advertiser_id` int(11) unsigned DEFAULT NULL,
  `ad_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `u_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'URL ID' ,
  `counter` smallint(11) unsigned DEFAULT NULL,
  `cycles_cycles` int(11) unsigned NOT NULL,
  `country` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `sat_id` int(11) NOT NULL,
  `server_type` tinyint(2) DEFAULT NULL,
  `server_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `collected` tinyint(1) NOT NULL DEFAULT '0',
  `date` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ad_uid`,`u_id`,`country`,`sat_id`,`date`),
  KEY `id` (`id`) USING HASH,
  KEY `collected` (`collected`) USING HASH,
  KEY `server_type` (`server_type`) USING HASH,
  KEY `server_name` (`server_name`) USING HASH,
  KEY `u_id` (`u_id`) USING HASH,
  KEY `sat_id` (`sat_id`) USING HASH,
  KEY `date` (`date`) USING HASH,
  KEY `advertiser_id_fk__impression` (`advertiser_id`) USING HASH,
  KEY `advert_id_fk__impression` (`advert_id`) USING HASH,
  KEY `country` (`country`) USING HASH,
  SHARD KEY `__SHARDKEY` (`ad_uid`,`u_id`,`country`,`sat_id`,`date`),
  SORT KEY `__UNORDERED` ()
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
