CREATE TABLE `media_report_url_clean` (
  `urlCleanId` bigint(20) NOT NULL DEFAULT '0',
  `cmPlacementId` bigint(20) NOT NULL DEFAULT '0',
  `cmCreativeId` bigint(20) NOT NULL DEFAULT '0',
  `googleAdsAdId` bigint(20) NOT NULL DEFAULT '0',
  `linkedinCreativeId` bigint(20) NOT NULL DEFAULT '0',
  `facebookAdId` bigint(20) NOT NULL DEFAULT '0',
  `date` date NOT NULL,
  `entrances` int(10) NOT NULL DEFAULT '0',
  `duplicateEntrances` int(10) NOT NULL DEFAULT '0',
  `duplicateEntrancesUnique` int(10) NOT NULL DEFAULT '0',
  `bounceEntrances` int(10) NOT NULL DEFAULT '0',
  `bounces` int(10) NOT NULL DEFAULT '0',
  `sessions` int(10) NOT NULL DEFAULT '0',
  `humanDirectEntrance` int(10) NOT NULL DEFAULT '0',
  `humanDirectBounce` int(10) NOT NULL DEFAULT '0',
  `humanPostClickEntrance` int(10) NOT NULL DEFAULT '0',
  `humanPostClickBounce` int(10) NOT NULL DEFAULT '0',
  `botDirectEntrance` int(10) NOT NULL DEFAULT '0',
  `botDirectBounce` int(10) NOT NULL DEFAULT '0',
  `botPostClickEntrance` int(10) NOT NULL DEFAULT '0',
  `botPostClickBounce` int(10) NOT NULL DEFAULT '0',
  `alphixEngaged` int(10) NOT NULL DEFAULT '0',
  `alphixUnengaged` int(10) NOT NULL DEFAULT '0',
  `timeOnPageView` int(10) NOT NULL DEFAULT '0',
  `timeOnPageSecond` decimal(20,5) NOT NULL DEFAULT '0',
  `events` int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`urlCleanId`,`cmPlacementId`,`cmCreativeId`,`googleAdsAdId`,`linkedinCreativeId`,`date`,`facebookAdId`),
  SHARD KEY `__SHARDKEY` (`urlCleanId`,`cmPlacementId`,`cmCreativeId`,`googleAdsAdId`,`linkedinCreativeId`,`date`,`facebookAdId`),
  SORT KEY `__UNORDERED` ()
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`;
