CREATE TABLE `aa_report_page_marketing_channel` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `organizationId` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `rsid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `date` date NOT NULL,
  `marketing_channel` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `page_url` varchar(2048) CHARACTER SET utf8mb4 NOT NULL,
  `clean_page_url` varchar(512) CHARACTER SET utf8mb4 NOT NULL,
  `url_clean_id` int(10) unsigned DEFAULT NULL,
  `url_clean_processed` datetime DEFAULT NULL,
  `booking_unique_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `booking_placement_id` int(10) unsigned DEFAULT NULL,
  `booking_creative_id` int(10) unsigned DEFAULT NULL,
  `users` int(11) NOT NULL DEFAULT '0',
  `sessions` int(11) NOT NULL DEFAULT '0',
  `entrances` int(11) NOT NULL DEFAULT '0',
  `bounces` int(11) NOT NULL DEFAULT '0',
  `time_on_page` int(11) NOT NULL DEFAULT '0',
  `time_on_site` int(11) NOT NULL DEFAULT '0',
  `pageviews` int(11) NOT NULL DEFAULT '0',
  `exits` int(11) NOT NULL DEFAULT '0',
  `occurrences` int(11) NOT NULL DEFAULT '0',
  `single_page_visits` int(11) NOT NULL DEFAULT '0',
  `time_per_visit` int(11) NOT NULL DEFAULT '0',
  `delta_tag_unique` int(10) unsigned DEFAULT NULL,
  `delta_tag_unique_processed` datetime DEFAULT NULL,
  `booking_line_item_id` bigint(20) unsigned DEFAULT NULL,
  `facebook_ad_id` bigint(20) unsigned DEFAULT NULL,
  `linkedin_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `twitter_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `dynamic_unique_number` int(10) unsigned DEFAULT NULL,
  `amx_line_item_id` bigint(20) unsigned DEFAULT NULL,
  `amx_auction_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `linkedin_creative_id` bigint(20) unsigned DEFAULT NULL,
  `smart_placement_stream_id` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `google_ads_ad_id` bigint(20) unsigned DEFAULT NULL,
  `google_ads_keyword` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `google_ads_placement_category_id` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `alphix_ledger` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `google_ads_ad_group_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `organizationId` (`organizationId`),
  KEY `rsid` (`rsid`),
  KEY `date` (`date`),
  KEY `marketing_channel` (`marketing_channel`),
  KEY `clean_page_url` (`clean_page_url`),
  KEY `booking_unique_number` (`booking_unique_number`),
  KEY `booking_placement_id` (`booking_placement_id`),
  KEY `booking_creative_id` (`booking_creative_id`),
  KEY `delta_tag_unique` (`delta_tag_unique`),
  KEY `delta_tag_unique_processed` (`delta_tag_unique_processed`),
  KEY `url_clean_id` (`url_clean_id`),
  KEY `booking_line_item_id` (`booking_line_item_id`),
  KEY `facebook_ad_id` (`facebook_ad_id`),
  KEY `linkedin_campaign_id` (`linkedin_campaign_id`),
  KEY `twitter_campaign_id` (`twitter_campaign_id`),
  KEY `dynamic_unique_number` (`dynamic_unique_number`),
  KEY `amx_line_item_id` (`amx_line_item_id`),
  KEY `amx_auction_id` (`amx_auction_id`),
  KEY `linkedin_creative_id` (`linkedin_creative_id`) USING BTREE,
  KEY `smart_placement_stream_id` (`smart_placement_stream_id`) USING BTREE,
  KEY `test_google_ads_ad_id_IDX` (`google_ads_ad_id`) USING BTREE,
  KEY `test_google_ads_keyword_IDX` (`google_ads_keyword`) USING BTREE,
  KEY `test_google_ads_placement_category_id_IDX` (`google_ads_placement_category_id`) USING BTREE,
  KEY `test_alphix_ledger_IDX` (`alphix_ledger`) USING BTREE,
  KEY `test_google_ads_ad_group_id_IDX` (`google_ads_ad_group_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=24453938 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
