CREATE TABLE `aw_report_ad` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `customer_id` bigint(20) unsigned NOT NULL,
  `ad_id` bigint(20) unsigned NOT NULL,
  `campaign_id` bigint(20) unsigned NOT NULL,
  `ad_group_id` bigint(20) unsigned NOT NULL,
  `ad_group_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `quality_score_avg` decimal(18,8) DEFAULT NULL,
  `avg_pos` decimal(18,8) DEFAULT NULL,
  `cost` decimal(10,2) NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `average_time_on_site` decimal(10,4) DEFAULT NULL,
  `all_conversions` decimal(10,2) DEFAULT NULL,
  `bounce_rate` decimal(10,2) DEFAULT NULL,
  `average_pageviews` decimal(10,4) DEFAULT NULL,
  `percent_new_visitors` decimal(10,2) DEFAULT NULL,
  `conversion_rate` decimal(10,2) DEFAULT NULL,
  `ad_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `display_url` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headline` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headline_part1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headline_part2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `image_ad_url` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `image_creative_image_height` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `image_creative_image_width` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `image_creative_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `path1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `path2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `creative_destination_url` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `creative_final_urls` json DEFAULT NULL COMMENT '(DC2Type:json)',
  `conversions` decimal(10,2) DEFAULT NULL,
  `cost_gbp` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `campaign_id` (`campaign_id`),
  KEY `ad_id` (`ad_id`),
  KEY `customer_id` (`customer_id`),
  KEY `ad_group_id` (`ad_group_id`),
  KEY `cost_gbp` (`cost_gbp`)
) ENGINE=InnoDB AUTO_INCREMENT=8938958 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
