CREATE TABLE `aw_report` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `customer_id` bigint(20) unsigned NOT NULL,
  `campaign_id` bigint(20) unsigned NOT NULL,
  `avg_pos` decimal(18,8) DEFAULT NULL,
  `cost` decimal(10,2) NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `average_time_on_site` decimal(10,4) DEFAULT NULL,
  `all_conversions` decimal(10,2) DEFAULT NULL,
  `bounce_rate` decimal(10,2) DEFAULT NULL,
  `search_impression_share` decimal(15,12) DEFAULT NULL,
  `search_rank_lost_impression_share` decimal(15,12) DEFAULT NULL,
  `search_budget_lost_impression_share` decimal(15,12) DEFAULT NULL,
  `average_pageviews` decimal(10,4) DEFAULT NULL,
  `percent_new_visitors` decimal(10,2) DEFAULT NULL,
  `conversion_rate` decimal(10,2) DEFAULT NULL,
  `measurable_impressions` int(11) DEFAULT NULL,
  `viewable_impressions` int(11) DEFAULT NULL,
  `network` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `network_inc_partners` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `conversions` decimal(10,2) DEFAULT NULL,
  `cost_gbp` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `campaign_id` (`campaign_id`),
  KEY `customer_id` (`customer_id`),
  KEY `cost_gbp` (`cost_gbp`),
  KEY `network` (`network`)
) ENGINE=InnoDB AUTO_INCREMENT=3276027 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
