CREATE TABLE `aw_report_device` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `customer_id` bigint(20) unsigned NOT NULL,
  `campaign_id` bigint(20) unsigned NOT NULL,
  `device` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `avg_pos` decimal(18,8) NOT NULL,
  `cost` decimal(10,2) NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `all_conversions` decimal(10,2) DEFAULT NULL,
  `search_impression_share` decimal(15,12) DEFAULT NULL,
  `search_rank_lost_impression_share` decimal(15,12) DEFAULT NULL,
  `search_budget_lost_impression_share` decimal(15,12) DEFAULT NULL,
  `conversion_rate` decimal(10,2) DEFAULT NULL,
  `measurable_impressions` int(11) DEFAULT NULL,
  `viewable_impressions` int(11) DEFAULT NULL,
  `network` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `network_inc_partners` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `conversions` decimal(10,2) DEFAULT NULL,
  `cost_gbp` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `campaign_id` (`campaign_id`),
  KEY `device` (`device`),
  KEY `cost_gbp` (`cost_gbp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
