CREATE TABLE `aw_report_ad_group_keyword` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `customer_id` bigint(20) unsigned NOT NULL,
  `campaign_id` bigint(20) unsigned NOT NULL,
  `ad_group_id` bigint(20) unsigned NOT NULL,
  `ad_group_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `keyword_id` bigint(20) unsigned DEFAULT NULL,
  `keyword` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `quality_score_avg` decimal(18,8) DEFAULT NULL,
  `avg_pos` decimal(18,8) DEFAULT NULL,
  `cost` decimal(10,2) NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `average_time_on_site` decimal(10,4) DEFAULT NULL,
  `all_conversions` decimal(10,2) DEFAULT NULL,
  `bounce_rate` decimal(10,2) DEFAULT NULL,
  `search_impression_share` decimal(15,12) DEFAULT NULL,
  `search_rank_lost_impression_share` decimal(15,12) DEFAULT NULL,
  `average_pageviews` decimal(10,4) DEFAULT NULL,
  `percent_new_visitors` decimal(10,2) DEFAULT NULL,
  `conversion_rate` decimal(10,2) DEFAULT NULL,
  `conversions` decimal(10,2) DEFAULT NULL,
  `cost_gbp` decimal(10,2) DEFAULT NULL,
  `match_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `campaign_id` (`campaign_id`),
  KEY `ad_group_id` (`ad_group_id`),
  KEY `customer_id` (`customer_id`),
  KEY `keyword` (`keyword`),
  KEY `cost_gbp` (`cost_gbp`),
  KEY `match_type` (`match_type`)
) ENGINE=InnoDB AUTO_INCREMENT=34459881 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
