CREATE TABLE `aw_report_keyword` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `customer_id` bigint(20) unsigned NOT NULL,
  `campaign_id` bigint(20) unsigned NOT NULL,
  `keyword_id` bigint(20) unsigned DEFAULT NULL,
  `keyword` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `quality_score_avg` decimal(18,8) DEFAULT NULL,
  `avg_pos` decimal(18,8) DEFAULT NULL,
  `cost` decimal(10,2) NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `average_time_on_site` decimal(10,4) DEFAULT NULL,
  `all_conversions` decimal(10,2) DEFAULT NULL,
  `bounce_rate` decimal(10,2) DEFAULT NULL,
  `search_impression_share` decimal(15,12) DEFAULT NULL,
  `search_rank_lost_impression_share` decimal(15,12) DEFAULT NULL,
  `average_pageviews` decimal(10,4) DEFAULT NULL,
  `percent_new_visitors` decimal(10,2) DEFAULT NULL,
  `conversion_rate` decimal(10,2) DEFAULT NULL,
  `first_page_cpc` decimal(10,2) DEFAULT NULL,
  `top_of_page_cpc` decimal(10,2) DEFAULT NULL,
  `conversions` decimal(10,2) DEFAULT NULL,
  `cost_gbp` decimal(10,2) DEFAULT NULL,
  `match_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `campaign_id` (`campaign_id`),
  KEY `customer_id` (`customer_id`),
  KEY `keyword` (`keyword`),
  KEY `cost_gbp` (`cost_gbp`)
) ENGINE=InnoDB AUTO_INCREMENT=34472728 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
