CREATE TABLE `ax_advertiser` (
  `advertiserId` int(10) unsigned NOT NULL,
  `accountId` int(10) unsigned NOT NULL,
  `alternativeId` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `advertiserName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `defaultClickUrl` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `defaultContinent` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `defaultCurrency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `conversionMethodId` int(10) unsigned DEFAULT NULL,
  `attributes` longtext COLLATE utf8_unicode_ci,
  `defaultCampaignPresetId` longtext COLLATE utf8_unicode_ci,
  `defaultLineItemPresetId` longtext COLLATE utf8_unicode_ci,
  `enableSkadTracking` tinyint(1) DEFAULT NULL,
  `createDate` datetime NOT NULL,
  `updateDate` datetime NOT NULL,
  `notes` longtext COLLATE utf8_unicode_ci,
  `active` tinyint(1) NOT NULL,
  `syncd` datetime NOT NULL,
  `defaultCreativeThumbnailUrl` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`advertiserId`),
  KEY `accountId` (`accountId`),
  KEY `alternativeId` (`alternativeId`),
  KEY `advertiserName` (`advertiserName`),
  KEY `active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
