CREATE TABLE `ax_creative` (
  `creativeId` int(10) unsigned NOT NULL,
  `accountId` int(10) unsigned NOT NULL,
  `advertiserId` int(10) unsigned NOT NULL,
  `alternativeId` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `creativeType` int(10) unsigned DEFAULT NULL,
  `creativeTemplateId` int(10) unsigned DEFAULT NULL,
  `creativeStatusId` int(10) unsigned DEFAULT NULL,
  `creativeRuleId` int(10) unsigned DEFAULT NULL,
  `creativeRuleKey` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `width` int(10) unsigned DEFAULT NULL,
  `height` int(10) unsigned DEFAULT NULL,
  `sizeless` tinyint(1) DEFAULT NULL,
  `secure` tinyint(1) DEFAULT NULL,
  `clickUrl` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL,
  `creativeName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `creativeAttributes` longtext COLLATE utf8_unicode_ci,
  `creativeAssets` longtext COLLATE utf8_unicode_ci,
  `primaryAsset` longtext COLLATE utf8_unicode_ci,
  `secondaryAsset` longtext COLLATE utf8_unicode_ci,
  `creativeContent` longtext COLLATE utf8_unicode_ci,
  `previewToken` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `creativeThumbnailUrl` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `startDate` date DEFAULT NULL,
  `endDate` date DEFAULT NULL,
  `frequencyCap` longtext COLLATE utf8_unicode_ci,
  `scripts` longtext COLLATE utf8_unicode_ci,
  `pixels` longtext COLLATE utf8_unicode_ci,
  `events` longtext COLLATE utf8_unicode_ci,
  `progressEvents` longtext COLLATE utf8_unicode_ci,
  `pushStatus` int(10) unsigned DEFAULT NULL,
  `pushUpdate` tinyint(1) DEFAULT NULL,
  `createDate` datetime NOT NULL,
  `updateDate` datetime NOT NULL,
  `notes` longtext COLLATE utf8_unicode_ci,
  `active` tinyint(1) NOT NULL,
  `syncd` datetime NOT NULL,
  `creativeContentMunge` longtext COLLATE utf8_unicode_ci,
  `creativeContentTag` longtext COLLATE utf8_unicode_ci,
  PRIMARY KEY (`creativeId`),
  KEY `accountId` (`accountId`),
  KEY `advertiserId` (`advertiserId`),
  KEY `alternativeId` (`alternativeId`),
  KEY `creativeName` (`creativeName`),
  KEY `active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
