CREATE TABLE `ax_campaign` (
  `campaignId` int(10) unsigned NOT NULL,
  `accountId` int(10) unsigned NOT NULL,
  `advertiserId` int(10) unsigned NOT NULL,
  `alternativeId` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaignName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `campaignBudget` int(11) DEFAULT NULL,
  `campaignSpend` int(11) DEFAULT NULL,
  `dailyBudget` int(11) DEFAULT NULL,
  `budgetType` int(10) unsigned DEFAULT NULL,
  `startDate` date DEFAULT NULL,
  `endDate` date DEFAULT NULL,
  `pacing` int(10) unsigned DEFAULT NULL,
  `bidModifierId` int(10) unsigned DEFAULT NULL,
  `deliveryModifierId` int(10) unsigned DEFAULT NULL,
  `maxBid` int(10) unsigned DEFAULT NULL,
  `testPlanId` int(10) unsigned DEFAULT NULL,
  `revenueType` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `revenueAmount` int(10) unsigned DEFAULT NULL,
  `frequencyCapDuration` int(10) unsigned DEFAULT NULL,
  `frequencyCapImpressions` int(10) unsigned DEFAULT NULL,
  `frequencyCapType` int(10) unsigned DEFAULT NULL,
  `frequencyCapVendor` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `defaultTargeting` longtext COLLATE utf8_unicode_ci,
  `continents` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `currency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `segmentExtensionDefault` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `segmentExtensionTypeDefault` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `segmentExtensionVendorsDefault` longtext COLLATE utf8_unicode_ci,
  `enableSkadTracking` tinyint(1) DEFAULT NULL,
  `pushStatus` int(10) unsigned DEFAULT NULL,
  `pushUpdate` int(10) unsigned DEFAULT NULL,
  `createDate` datetime NOT NULL,
  `updateDate` datetime NOT NULL,
  `notes` longtext COLLATE utf8_unicode_ci,
  `active` tinyint(1) NOT NULL,
  `syncd` datetime NOT NULL,
  PRIMARY KEY (`campaignId`),
  KEY `accountId` (`accountId`),
  KEY `advertiserId` (`advertiserId`),
  KEY `alternativeId` (`alternativeId`),
  KEY `campaignName` (`campaignName`),
  KEY `startDate` (`startDate`),
  KEY `endDate` (`endDate`),
  KEY `active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
