CREATE TABLE `ax_line_item` (
  `lineItemId` int(10) unsigned NOT NULL,
  `accountId` int(10) unsigned NOT NULL,
  `advertiserId` int(10) unsigned NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `alternativeId` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lineItemTypeId` int(10) unsigned DEFAULT NULL,
  `targetingTemplateId` int(10) unsigned DEFAULT NULL,
  `lineItemVersion` int(10) unsigned DEFAULT NULL,
  `lineItemName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `lineItemBudget` int(11) DEFAULT NULL,
  `dailyBudget` int(11) DEFAULT NULL,
  `budgetType` int(10) unsigned DEFAULT NULL,
  `lineItemSpend` decimal(15,4) DEFAULT NULL,
  `currency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `frequencyCapDuration` int(10) unsigned DEFAULT NULL,
  `frequencyCapImpressions` int(10) unsigned DEFAULT NULL,
  `frequencyCapType` int(10) unsigned DEFAULT NULL,
  `frequencyCapVendor` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `biddingStrategy` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `biddingBidShading` tinyint(1) DEFAULT NULL,
  `biddingBidShadingWinRateControl` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `biddingValues` longtext COLLATE utf8_unicode_ci,
  `biddingCustom` tinyint(1) DEFAULT NULL,
  `biddingPacing` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `creativeWeightingMethod` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pacing` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bidModifierId` int(10) unsigned DEFAULT NULL,
  `deliveryModifierId` int(10) unsigned DEFAULT NULL,
  `maxBid` decimal(15,4) DEFAULT NULL,
  `testPlanId` int(10) unsigned DEFAULT NULL,
  `revenueType` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `revenueAmount` decimal(15,4) DEFAULT NULL,
  `startDate` date DEFAULT NULL,
  `endDate` date DEFAULT NULL,
  `segmentExtensionDefault` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `segmentExtensionTypeDefault` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `segmentExtensionVendorsDefault` longtext COLLATE utf8_unicode_ci,
  `enableSkadTracking` tinyint(1) DEFAULT NULL,
  `guaranteed` tinyint(1) DEFAULT NULL,
  `targetSkad` tinyint(1) DEFAULT NULL,
  `pushStatus` int(10) unsigned DEFAULT NULL,
  `pushUpdate` tinyint(1) DEFAULT NULL,
  `userTimezones` longtext COLLATE utf8_unicode_ci,
  `createDate` datetime NOT NULL,
  `updateDate` datetime NOT NULL,
  `notes` longtext COLLATE utf8_unicode_ci,
  `active` tinyint(1) NOT NULL,
  `syncd` datetime NOT NULL,
  `skadAssignmentLevel` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`lineItemId`),
  KEY `accountId` (`accountId`),
  KEY `advertiserId` (`advertiserId`),
  KEY `campaignId` (`campaignId`),
  KEY `alternativeId` (`alternativeId`),
  KEY `lineItemName` (`lineItemName`),
  KEY `active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
