CREATE TABLE `ax_segment` (
  `segmentId` int(10) unsigned NOT NULL,
  `segmentKey` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `accountId` int(10) unsigned NOT NULL,
  `advertiserId` int(10) unsigned NOT NULL,
  `segmentName` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dataProviderBillingKey` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `segmentDescription` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cpmCost` decimal(15,5) unsigned DEFAULT NULL,
  `ttlDays` int(10) unsigned NOT NULL,
  `verbUsage` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `aggregateExcludes` tinyint(1) NOT NULL DEFAULT '0',
  `extensible` tinyint(1) NOT NULL DEFAULT '0',
  `createDate` datetime NOT NULL,
  `updateDate` datetime NOT NULL,
  `alternativeId` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `notes` mediumtext COLLATE utf8_unicode_ci,
  `active` tinyint(1) NOT NULL,
  PRIMARY KEY (`segmentId`) USING BTREE,
  KEY `segmentKey` (`segmentKey`) USING BTREE,
  KEY `accountId` (`accountId`) USING BTREE,
  KEY `advertiserId` (`advertiserId`) USING BTREE,
  KEY `segmentName` (`segmentName`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
