CREATE TABLE `bk_category` (
  `id` int(10) unsigned NOT NULL,
  `partner_id` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `notes` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `parent_category_id` int(10) unsigned NOT NULL,
  `vertical_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `visibility_status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `category_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `is_public_flag` tinyint(1) NOT NULL,
  `is_countable_flag` tinyint(1) NOT NULL,
  `is_for_navigation_only_flag` tinyint(1) NOT NULL,
  `is_include_for_analytics_flag` tinyint(1) NOT NULL,
  `is_mutually_exclusive_children_flag` tinyint(1) NOT NULL,
  `is_explicit_price_floor_flag` tinyint(1) NOT NULL,
  `sort_order` int(10) unsigned NOT NULL,
  `price_floor` decimal(10,0) NOT NULL,
  `ownership_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `is_leaf_flag` tinyint(1) NOT NULL,
  `node_owner_id` int(10) unsigned NOT NULL,
  `path_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `path_name` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
