CREATE TABLE `bk_campaign` (
  `id` int(10) unsigned NOT NULL,
  `partner_id` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `bid` decimal(10,0) NOT NULL,
  `pacing_goal` decimal(10,0) NOT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `activated` tinyint(1) NOT NULL,
  `include_top_nodes` tinyint(1) NOT NULL,
  `pacing_type` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `category_transfer_method` int(10) unsigned NOT NULL,
  `https_pull` tinyint(1) NOT NULL,
  `negative_revenue` tinyint(1) NOT NULL,
  `targeting_source` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `win_frequency` int(10) unsigned NOT NULL,
  `campaign_type` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `revenue_recognition` tinyint(1) NOT NULL,
  `test_campaign` tinyint(1) NOT NULL,
  `id_swap` tinyint(1) NOT NULL,
  `json_pull_macro` tinyint(1) NOT NULL,
  `pricing_model_id` int(10) unsigned NOT NULL,
  `pricing_model_name` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `solution_type_id` int(10) unsigned NOT NULL,
  `solution_type_name` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `recency` int(11) NOT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` date DEFAULT NULL,
  `updated_at` date DEFAULT NULL,
  `labels` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL,
  `priority` int(10) unsigned NOT NULL,
  `partner_sites_only` tinyint(1) NOT NULL,
  `realtime_targeting` tinyint(1) NOT NULL,
  `offline_targeting` tinyint(1) NOT NULL,
  `suspended` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
