CREATE TABLE `dbm_line_item` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `line_item_id` bigint(20) unsigned NOT NULL,
  `insertion_order_id` bigint(20) unsigned NOT NULL,
  `advertiser_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `budget_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `budget_amount` decimal(15,2) DEFAULT NULL,
  `pacing` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pacing_rate` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pacing_amount` decimal(15,2) DEFAULT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `dealType` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `margin` decimal(10,2) DEFAULT NULL,
  `targetingSite` tinyint(1) DEFAULT NULL,
  `targetingAudience` tinyint(1) DEFAULT NULL,
  `targetingKeyWord` tinyint(1) DEFAULT NULL,
  `targetingBrandSafety` tinyint(1) DEFAULT NULL,
  `targetingViewability` tinyint(1) DEFAULT NULL,
  `targetingGeo` tinyint(1) DEFAULT NULL,
  `targetingLanguage` tinyint(1) DEFAULT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `line_item_id` (`line_item_id`),
  KEY `start_date` (`start_date`),
  KEY `end_date` (`end_date`),
  KEY `insertion_order_id` (`insertion_order_id`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`),
  KEY `status` (`status`),
  KEY `advertiser_id` (`advertiser_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1572900 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
