CREATE TABLE `dbm_reports_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `advertiser` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `advertiserId` bigint(20) unsigned NOT NULL,
  `creative` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `creativeId` bigint(20) unsigned NOT NULL,
  `creativeSize` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `advertiserCurrency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `partnerCurrency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaign` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaignId` bigint(20) unsigned NOT NULL,
  `insertionOrder` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `insertionOrderId` bigint(20) unsigned NOT NULL,
  `lineItem` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lineItemId` bigint(20) unsigned NOT NULL,
  `inventorySource` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `inventorySourceId` bigint(20) unsigned NOT NULL,
  `inventorySourceType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `inventorySourceIdEx` bigint(20) NOT NULL COMMENT 'Inventory Source Id External',
  `publicInventory` int(11) DEFAULT NULL,
  `appUrl` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `appUrlId` bigint(20) unsigned NOT NULL,
  `impressions` int(11) NOT NULL,
  `billableImpressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `ctr` double NOT NULL DEFAULT '0',
  `totalConversions` int(11) NOT NULL,
  `totalPostClickConversions` int(11) NOT NULL,
  `postViewConversions` int(11) NOT NULL,
  `avImpressions` int(11) NOT NULL,
  `revenue` double NOT NULL DEFAULT '0',
  `mediaCost` double NOT NULL DEFAULT '0',
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
