CREATE TABLE `dbm_inventory_source` (
  `inventorySourceId` int(11) unsigned NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `displayName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `commitment` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deliveryMethod` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dealId` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entityStatus` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sellerStatus` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `exchange` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `publisherName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `inventorySourceType` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `inventorySourceProductType` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `updateTime` datetime NOT NULL,
  `startTime` datetime NOT NULL,
  `endTime` datetime NOT NULL,
  `accountId` int(10) DEFAULT NULL,
  `profileId` int(10) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`inventorySourceId`) USING BTREE,
  KEY `commitment` (`commitment`) USING BTREE,
  KEY `updateTime` (`updateTime`) USING BTREE,
  KEY `startTime` (`startTime`) USING BTREE,
  KEY `endTime` (`endTime`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
