CREATE TABLE `dbm_report_campaign_cost` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `advertiserId` bigint(20) unsigned NOT NULL,
  `advertiserCurrency` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaignId` bigint(20) unsigned NOT NULL,
  `campaign` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `insertionOrderId` bigint(20) unsigned NOT NULL,
  `lineItemId` bigint(20) unsigned NOT NULL,
  `appUrlId` bigint(20) unsigned NOT NULL,
  `appUrl` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `impressions` int(11) NOT NULL,
  `billableImpressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `totalConversions` int(11) NOT NULL,
  `postClickConversions` int(11) NOT NULL,
  `postViewConversions` int(11) NOT NULL,
  `revenue` double NOT NULL DEFAULT '0',
  `mediaCost` double NOT NULL DEFAULT '0',
  `totalMediaCost` double NOT NULL DEFAULT '0',
  `audioCostECPCL` double NOT NULL DEFAULT '0',
  `audioRevenueECPCL` double NOT NULL DEFAULT '0',
  `cost` double NOT NULL DEFAULT '0',
  `costECPA` double NOT NULL DEFAULT '0',
  `costECPAPC` double NOT NULL DEFAULT '0',
  `costECPAPV` double NOT NULL DEFAULT '0',
  `costECPC` double NOT NULL DEFAULT '0',
  `costECPM` double NOT NULL DEFAULT '0',
  `costViewableECPM` double NOT NULL DEFAULT '0',
  `revenueECPA` double NOT NULL DEFAULT '0',
  `revenueECPAPC` double NOT NULL DEFAULT '0',
  `revenueECPAPV` double NOT NULL DEFAULT '0',
  `revenueECPC` double NOT NULL DEFAULT '0',
  `revenueECPM` double NOT NULL DEFAULT '0',
  `revenueViewableECPM` double NOT NULL DEFAULT '0',
  `videoCostECPCV` double NOT NULL DEFAULT '0',
  `videoRevenueECPCV` double NOT NULL DEFAULT '0',
  `comScoreVCE` double NOT NULL DEFAULT '0',
  `CPMfee1` double NOT NULL DEFAULT '0',
  `CPMfee2` double NOT NULL DEFAULT '0',
  `CPMfee3` double NOT NULL DEFAULT '0',
  `CPMfee4` double NOT NULL DEFAULT '0',
  `CPMfee5` double NOT NULL DEFAULT '0',
  `dataFees` double NOT NULL DEFAULT '0',
  `mediaFee1` double NOT NULL DEFAULT '0',
  `mediaFee2` double NOT NULL DEFAULT '0',
  `mediaFee3` double NOT NULL DEFAULT '0',
  `mediaFee4` double NOT NULL DEFAULT '0',
  `mediaFee5` double NOT NULL DEFAULT '0',
  `nielsenDigitalAdRatingsFee` double NOT NULL DEFAULT '0',
  `audioMediaCostECPCL` double NOT NULL DEFAULT '0',
  `mediaCostECPA` double NOT NULL DEFAULT '0',
  `mediaCostECPAPC` double NOT NULL DEFAULT '0',
  `mediaCostECPAPV` double NOT NULL DEFAULT '0',
  `mediaCostECPC` double NOT NULL DEFAULT '0',
  `mediaCostECPM` double NOT NULL DEFAULT '0',
  `mediaCostViewableECPM` double NOT NULL DEFAULT '0',
  `totalAudioMediaCostECPCL` double NOT NULL DEFAULT '0',
  `totalMediaCostECPA` double NOT NULL DEFAULT '0',
  `totalMediaCostECPAPC` double NOT NULL DEFAULT '0',
  `totalMediaCostECPAPV` double NOT NULL DEFAULT '0',
  `totalMediaCostECPC` double NOT NULL DEFAULT '0',
  `totalMediaCostECPM` double NOT NULL DEFAULT '0',
  `totalMediaCostViewableECPM` double NOT NULL DEFAULT '0',
  `totalVideoMediaCostECPCV` double NOT NULL DEFAULT '0',
  `videoMediaCostECPCV` double NOT NULL DEFAULT '0',
  `profit` double NOT NULL DEFAULT '0',
  `profitECPM` double NOT NULL DEFAULT '0',
  `profitViewableECPM` double NOT NULL DEFAULT '0',
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `advertiserId` (`advertiserId`),
  KEY `campaignId` (`campaignId`),
  KEY `campaign` (`campaign`),
  KEY `insertionOrderId` (`insertionOrderId`),
  KEY `lineItemId` (`lineItemId`),
  KEY `appUrlId` (`appUrlId`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`)
) ENGINE=InnoDB AUTO_INCREMENT=35926188 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
