CREATE TABLE `dc_ad` (
  `adId` int(11) NOT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  `subaccountId` int(10) unsigned NOT NULL,
  `advertiserId` int(10) unsigned NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `active` tinyint(1) NOT NULL,
  `archived` tinyint(1) NOT NULL,
  `startTime` datetime DEFAULT NULL,
  `endTime` datetime DEFAULT NULL,
  `sslRequired` tinyint(1) DEFAULT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `creativeRotation` longtext COLLATE utf8_unicode_ci,
  `clickThroughUrl` longtext COLLATE utf8_unicode_ci,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `latest_change_log` datetime DEFAULT NULL,
  PRIMARY KEY (`adId`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`),
  KEY `advertiserId` (`advertiserId`),
  KEY `active` (`active`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
