CREATE TABLE `dc_advertisers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `advertiserId` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `subaccountId` int(10) unsigned NOT NULL,
  `floodlightConfigurationId` int(10) unsigned NOT NULL,
  `originalFloodlightConfigurationId` int(10) unsigned NOT NULL,
  `advertiserGroupId` int(10) unsigned NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `defaultEmail` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clickThroughUrlSuffix` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `defaultClickThroughEventTagId` int(10) unsigned NOT NULL,
  `suspended` int(10) unsigned NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `latest_change_log` datetime DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `advertiserId` (`advertiserId`),
  KEY `idx_dc_advertisers_status` (`status`),
  KEY `idx_dc_advertisers_name` (`name`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`)
) ENGINE=InnoDB AUTO_INCREMENT=1470320 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
