CREATE TABLE `dc_change_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `change_log_id` bigint(20) unsigned NOT NULL,
  `object_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `object_id` bigint(20) unsigned NOT NULL,
  `transaction_id` bigint(20) unsigned NOT NULL,
  `user_profile_id` bigint(20) unsigned NOT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `user_profile_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `change_time` datetime NOT NULL,
  `action` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `field_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `old_value` longtext COLLATE utf8_unicode_ci NOT NULL,
  `new_value` longtext COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `change_log_id` (`change_log_id`),
  KEY `object_type` (`object_type`),
  KEY `object_id` (`object_id`),
  KEY `user_profile_id` (`user_profile_id`),
  KEY `user_profile_name` (`user_profile_name`),
  KEY `change_time` (`change_time`),
  KEY `action` (`action`),
  KEY `field_name` (`field_name`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`)
) ENGINE=InnoDB AUTO_INCREMENT=5793179 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
