CREATE TABLE `dc_campaigns` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `campaignId` int(10) unsigned NOT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `subaccountId` int(10) unsigned NOT NULL,
  `advertiserId` int(10) unsigned NOT NULL,
  `advertiserGroupId` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `archived` tinyint(1) NOT NULL,
  `startDate` date NOT NULL,
  `endDate` date NOT NULL,
  `billingInvoiceCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comment` mediumtext COLLATE utf8mb4_unicode_ci,
  `nielsenOcrEnabled` tinyint(1) NOT NULL,
  `createDate` date NOT NULL,
  `lastModifiedDate` date NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `latest_change_log` datetime DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `campaignId` (`campaignId`),
  KEY `idx_dc_campaigns_advertiserId` (`advertiserId`),
  KEY `idx_dc_campaigns_startDate` (`startDate`),
  KEY `idx_dc_campaigns_endDate` (`endDate`),
  KEY `idx_dc_campaigns_archived` (`archived`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`)
) ENGINE=InnoDB AUTO_INCREMENT=18702 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
