CREATE TABLE `dc_creatives_assets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `creativesId` int(10) unsigned NOT NULL,
  `creativeAssetId` int(10) unsigned NOT NULL,
  `size` int(10) unsigned DEFAULT NULL,
  `fileSize` int(10) unsigned DEFAULT NULL,
  `assetOriginalFile` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assetLocalFile` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assetSignedUrl` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assetSignedUrlDate` date DEFAULT NULL,
  `saved` tinyint(1) DEFAULT NULL,
  `savedDate` datetime DEFAULT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `flashVersion` int(10) unsigned DEFAULT NULL,
  `actionScript3` tinyint(1) DEFAULT NULL,
  `zipFilename` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `zipFilesize` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `displayType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `artworkType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `collapsedSize` int(10) unsigned DEFAULT NULL,
  `zIndex` int(10) unsigned DEFAULT NULL,
  `windowMode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transparency` tinyint(1) DEFAULT NULL,
  `pushdown` tinyint(1) DEFAULT NULL,
  `pushdownDuration` double DEFAULT NULL,
  `positionTopUnit` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `positionLeftUnit` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `verticallyLocked` tinyint(1) DEFAULT NULL,
  `horizontallyLocked` tinyint(1) DEFAULT NULL,
  `startTimeType` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customStartTimeValue` int(10) unsigned DEFAULT NULL,
  `durationType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duration` int(10) unsigned DEFAULT NULL,
  `hideFlashObjects` tinyint(1) DEFAULT NULL,
  `hideSelectionBoxes` tinyint(1) DEFAULT NULL,
  `alignment` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `childAssetType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `originalBackup` int(10) unsigned DEFAULT NULL,
  `bitRate` int(10) unsigned DEFAULT NULL,
  `mimeType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sslCompliant` tinyint(1) DEFAULT NULL,
  `progressiveServingUrl` mediumtext COLLATE utf8mb4_unicode_ci,
  `streamingServingUrl` mediumtext COLLATE utf8mb4_unicode_ci,
  `videoDuration` double DEFAULT NULL,
  `expandedDimension` int(11) DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  `gcpPath` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `creativeAssetId` (`creativeAssetId`),
  KEY `idx_dc_creatives_assets_creativesId` (`creativesId`),
  KEY `idx_dc_creatives_assets_saved` (`saved`),
  KEY `idx_dc_creatives_assets_creativesId_creativeAssetId_saved` (`creativesId`,`creativeAssetId`,`saved`),
  KEY `idx_dc_creatives_assets_creativesId_saved_savedDate_role` (`creativesId`,`saved`,`savedDate`,`role`),
  KEY `idx_dc_creatives_assets_savedDate` (`savedDate`),
  KEY `idx_dc_creatives_assets_creativesId_saved_role` (`creativesId`,`saved`,`role`),
  KEY `assetSignedUrlDate` (`assetSignedUrlDate`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`),
  KEY `gcpPath` (`gcpPath`)
) ENGINE=InnoDB AUTO_INCREMENT=926852 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
