CREATE TABLE `dc_creative_placement` (
  `accountId` int(10) unsigned NOT NULL,
  `profileId` int(10) unsigned NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `siteId` int(11) NOT NULL,
  `placementId` int(11) NOT NULL,
  `creativeId` int(11) NOT NULL,
  `impressions` int(11) NOT NULL,
  `measurableImpressions` int(11) NOT NULL,
  `viewableImpressions` int(11) NOT NULL,
  `defaultImpressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `dateMin` date NOT NULL,
  `dateMax` date NOT NULL,
  PRIMARY KEY (`accountId`,`profileId`,`advertiserId`,`campaignId`,`siteId`,`placementId`,`creativeId`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`),
  KEY `advertiserId` (`advertiserId`),
  KEY `siteId` (`siteId`),
  KEY `campaignId` (`campaignId`),
  KEY `placementId` (`placementId`),
  KEY `creativeId` (`creativeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
