CREATE TABLE `dc_creatives` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `creativeId` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `renderingId` int(10) unsigned DEFAULT NULL,
  `advertiserId` int(10) unsigned DEFAULT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `subaccountId` int(10) unsigned DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL,
  `archived` tinyint(1) DEFAULT NULL,
  `version` int(10) unsigned DEFAULT NULL,
  `sizeId` int(10) unsigned NOT NULL,
  `lastModifiedInfo` datetime NOT NULL,
  `sslOverride` tinyint(1) DEFAULT NULL,
  `sslCompliant` tinyint(1) DEFAULT NULL,
  `dynamicAssetSelection` tinyint(1) DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `redirectUrl` mediumtext COLLATE utf8mb4_unicode_ci,
  `htmlCode` mediumtext COLLATE utf8mb4_unicode_ci,
  `htmlCodeLocked` mediumtext COLLATE utf8mb4_unicode_ci,
  `backgroundColor` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allowScriptAccess` tinyint(1) DEFAULT NULL,
  `backupImageClickThroughUrl` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authoringTool` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requiredFlashPluginVersion` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `artworkType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requiredFlashVersion` int(10) unsigned DEFAULT NULL,
  `thirdPartyBackupImageImpressionsUrl` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `thirdPartyRichMediaImpressionsUrl` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `totalFileSize` int(10) unsigned DEFAULT NULL,
  `videoDuration` double DEFAULT NULL,
  `commercialId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companionCreatives` int(10) unsigned DEFAULT NULL,
  `videoDescription` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `skippable` tinyint(1) DEFAULT NULL,
  `thirdPartyUrls` int(10) unsigned DEFAULT NULL,
  `adParameters` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `overrideCss` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `studioCreativeId` int(10) unsigned DEFAULT NULL,
  `studioTraffickedCreativeId` int(10) unsigned DEFAULT NULL,
  `latestTraffickedCreativeId` int(10) unsigned DEFAULT NULL,
  `studioAdvertiserId` int(10) unsigned DEFAULT NULL,
  `autoAdvanceImages` tinyint(4) DEFAULT NULL,
  `backupImageReportingLabel` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `convertFlashToHtml5` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `latest_change_log` datetime DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `creativeId` (`creativeId`),
  KEY `idx_dc_creatives_advertiserId` (`advertiserId`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`)
) ENGINE=InnoDB AUTO_INCREMENT=182832 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
