CREATE TABLE `dc_floodlight_activity` (
  `floodlightActivityId` int(11) unsigned NOT NULL,
  `floodlightActivityGroupId` int(11) unsigned NOT NULL,
  `floodlightConfigurationId` int(11) unsigned NOT NULL,
  `advertiserId` int(11) unsigned NOT NULL,
  `accountId` int(11) unsigned NOT NULL,
  `profileId` int(11) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tagString` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `expectedUrl` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `secure` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `countingMethod` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tagFormat` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `cacheBustingType` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `floodlightActivityGroupType` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `floodlightActivityGroupTagString` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `floodlightActivityGroupName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `floodlightTagType` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `sslCompliant` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `sslRequired` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `attributionEnabled` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`floodlightActivityId`) USING BTREE,
  KEY `floodlightActivityGroupId` (`floodlightActivityGroupId`) USING BTREE,
  KEY `floodlightConfigurationId` (`floodlightConfigurationId`) USING BTREE,
  KEY `advertiserId` (`advertiserId`) USING BTREE,
  KEY `accountId` (`accountId`) USING BTREE,
  KEY `profileId` (`profileId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
