CREATE TABLE `dc_placements` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `placementId` int(10) unsigned NOT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `subaccountId` int(10) unsigned NOT NULL,
  `advertiserId` int(10) unsigned NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `siteId` int(10) unsigned NOT NULL,
  `directorySiteId` int(10) unsigned NOT NULL,
  `paymentSource` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `compatibility` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sizeId` int(10) unsigned NOT NULL,
  `archived` tinyint(1) NOT NULL,
  `paymentApproved` tinyint(1) NOT NULL,
  `placementGroupId` int(10) unsigned NOT NULL,
  `isPrimary` tinyint(1) NOT NULL,
  `contentCategoryId` int(10) unsigned NOT NULL,
  `placementStrategyId` int(10) unsigned NOT NULL,
  `comment` mediumtext COLLATE utf8mb4_unicode_ci,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `publisherUpdateInfo` datetime NOT NULL,
  `createInfo` datetime NOT NULL,
  `lastModifiedInfo` datetime NOT NULL,
  `sslRequired` tinyint(1) NOT NULL,
  `externalId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bookingUniqueNumber` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bookingStartDate` date DEFAULT NULL,
  `bookingEndDate` date DEFAULT NULL,
  `bookingImpressions` int(10) DEFAULT NULL,
  `videoActiveViewOptOut` tinyint(1) NOT NULL,
  `vpaidAdapterChoice` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `adBlockingOptOut` tinyint(1) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `latest_change_log` datetime DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  `activeStatus` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_placementId` (`placementId`),
  KEY `idx_dc_placements_advertiserId` (`advertiserId`),
  KEY `idx_dc_placements_campaignId` (`campaignId`),
  KEY `idx_dc_placements_sizeId` (`sizeId`),
  KEY `externalId` (`externalId`),
  KEY `matchedBookingUniqueNumber` (`bookingUniqueNumber`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`)
) ENGINE=InnoDB AUTO_INCREMENT=279065 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
