CREATE TABLE `dc_reports_data_placement_creative` (
  `date` date NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `placementId` int(11) NOT NULL,
  `creativeId` int(11) NOT NULL,
  `siteId` int(11) NOT NULL,
  `size` varchar(1024) COLLATE utf8_unicode_ci NOT NULL,
  `clickRate` double DEFAULT NULL,
  `bookedImpressions` int(11) NOT NULL,
  `bookedClicks` int(11) NOT NULL,
  `interactionRate` double DEFAULT NULL,
  `interactiveImp` int(11) DEFAULT NULL,
  `richMediaClicks` int(11) DEFAULT NULL,
  `richMediaClickRate` double DEFAULT NULL,
  `richMediaImp` int(11) DEFAULT NULL,
  `avgInteractionTime` double DEFAULT NULL,
  `totalInterractionTime` int(11) DEFAULT NULL,
  `totalInterractions` int(11) DEFAULT NULL,
  `totalConversions` int(11) DEFAULT NULL,
  `clickThroughConv` int(11) DEFAULT NULL,
  `viewThroughConv` int(11) NOT NULL,
  `videoFirstQuatileCompletions` int(11) DEFAULT NULL,
  `videoThirdQuatileCompletions` int(11) DEFAULT NULL,
  `videoMidpoints` int(11) DEFAULT NULL,
  `videoCompletions` int(11) DEFAULT NULL,
  `videoPlays` int(11) DEFAULT NULL,
  `videoReplays` int(11) DEFAULT NULL,
  `videoViews` int(11) DEFAULT NULL,
  `videoInteractions` int(11) DEFAULT NULL,
  `expansions` int(11) DEFAULT NULL,
  `avViewableImpressions` int(11) NOT NULL,
  `avMeasurableImpressions` int(11) DEFAULT NULL,
  `excludeCode` tinyint(1) NOT NULL DEFAULT '0',
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`date`,`placementId`,`creativeId`),
  KEY `profileId` (`profileId`),
  KEY `accountId` (`accountId`),
  KEY `idx_dc_reports_data_date` (`date`),
  KEY `size` (`size`),
  KEY `idx_dc_reports_data_campaignId` (`campaignId`),
  KEY `idx_dc_reports_data_advertiserId` (`advertiserId`),
  KEY `idx_dc_reports_data_placementId` (`placementId`),
  KEY `idx_dc_reports_data_siteId` (`siteId`),
  KEY `idx_dc_reports_data_impressions` (`impressions`),
  KEY `idx_dc_reports_data_clicks` (`clicks`),
  KEY `idx_dc_reports_data_bookedImp` (`bookedImpressions`),
  KEY `idx_dc_reports_data_bookedClicks` (`bookedClicks`),
  KEY `excludeCode` (`excludeCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
