CREATE TABLE `dc_reports_data_platform` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `placementId` int(11) NOT NULL,
  `creativeId` int(11) NOT NULL,
  `siteId` int(11) NOT NULL,
  `size` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `creativeType` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `adType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `platform` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clickRate` double DEFAULT NULL,
  `bookedImpressions` int(11) NOT NULL,
  `bookedClicks` int(11) NOT NULL,
  `interactionRate` double DEFAULT NULL,
  `interactiveImp` int(11) DEFAULT NULL,
  `richMediaClicks` int(11) DEFAULT NULL,
  `richMediaClickRate` double DEFAULT NULL,
  `richMediaImp` int(11) DEFAULT NULL,
  `avgInteractionTime` double DEFAULT NULL,
  `totalInterractionTime` int(11) DEFAULT NULL,
  `totalInterractions` int(11) DEFAULT NULL,
  `totalConversions` int(11) DEFAULT NULL,
  `clickThroughConv` int(11) DEFAULT NULL,
  `viewThroughConv` int(11) NOT NULL,
  `videoFirstQuatileCompletions` int(11) DEFAULT NULL,
  `videoThirdQuatileCompletions` int(11) DEFAULT NULL,
  `videoMidpoints` int(11) DEFAULT NULL,
  `videoCompletions` int(11) DEFAULT NULL,
  `videoPlays` int(11) DEFAULT NULL,
  `videoReplays` int(11) DEFAULT NULL,
  `videoViews` int(11) DEFAULT NULL,
  `videoInteractions` int(11) DEFAULT NULL,
  `expansions` int(11) DEFAULT NULL,
  `avViewableImpressions` int(11) NOT NULL,
  `avMeasurableImpressions` int(11) DEFAULT NULL,
  `excludeCode` tinyint(1) NOT NULL DEFAULT '0',
  `browser` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `platform` (`platform`),
  KEY `idx_dc_reports_data_date` (`date`),
  KEY `idx_dc_reports_data_campaignId` (`campaignId`),
  KEY `idx_dc_reports_data_advertiserId` (`advertiserId`),
  KEY `idx_dc_reports_data_placementId` (`placementId`),
  KEY `idx_dc_reports_data_creativeId` (`creativeId`),
  KEY `idx_dc_reports_data_siteId` (`siteId`),
  KEY `idx_dc_reports_data_impressions` (`impressions`),
  KEY `idx_dc_reports_data_clicks` (`clicks`),
  KEY `idx_dc_reports_data_bookedImp` (`bookedImpressions`),
  KEY `idx_dc_reports_data_bookedClicks` (`bookedClicks`),
  KEY `excludeCode` (`excludeCode`),
  KEY `browser` (`browser`),
  KEY `size` (`size`),
  KEY `profileId` (`profileId`),
  KEY `accountId` (`accountId`)
) ENGINE=InnoDB AUTO_INCREMENT=181639066 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
