CREATE TABLE `dc_reports_data_landing_page` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `siteId` int(11) NOT NULL,
  `placementId` int(11) NOT NULL,
  `adId` int(11) NOT NULL,
  `creativeId` int(11) NOT NULL,
  `adType` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `landing_page` varchar(1024) COLLATE utf8_unicode_ci NOT NULL,
  `click_through_url` varchar(1024) COLLATE utf8_unicode_ci NOT NULL,
  `clean_landing_page` varchar(1024) COLLATE utf8_unicode_ci DEFAULT NULL,
  `clicks` int(11) NOT NULL,
  `excludeCode` tinyint(1) NOT NULL DEFAULT '0',
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  `url_clean_id` int(10) unsigned DEFAULT NULL,
  `url_clean_processed` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `campaignId` (`campaignId`),
  KEY `advertiserId` (`advertiserId`),
  KEY `placementId` (`placementId`),
  KEY `creativeId` (`creativeId`),
  KEY `siteId` (`siteId`),
  KEY `adId` (`adId`),
  KEY `clicks` (`clicks`),
  KEY `adType` (`adType`),
  KEY `excludeCode` (`excludeCode`),
  KEY `clean_landing_page` (`clean_landing_page`),
  KEY `profileId` (`profileId`),
  KEY `accountId` (`accountId`),
  KEY `url_clean_id` (`url_clean_id`),
  KEY `url_clean_processed` (`url_clean_processed`)
) ENGINE=InnoDB AUTO_INCREMENT=12446079 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
