CREATE TABLE `dc_reports_data_dbm_placement` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `campaignId` int(11) NOT NULL,
  `advertiserId` int(11) NOT NULL,
  `placementId` int(11) NOT NULL,
  `advertiserDbmId` int(11) NOT NULL,
  `siteDbmId` bigint(20) NOT NULL,
  `insertionOrderDbmId` int(11) NOT NULL,
  `lineItemDbmId` int(11) NOT NULL,
  `size` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `clickRate` double DEFAULT NULL,
  `bookedImpressions` int(11) NOT NULL,
  `bookedClicks` int(11) NOT NULL,
  `interactionRate` double DEFAULT NULL,
  `interactiveImp` int(11) DEFAULT NULL,
  `richMediaClicks` int(11) DEFAULT NULL,
  `richMediaClickRate` double DEFAULT NULL,
  `richMediaImp` int(11) DEFAULT NULL,
  `avgInteractionTime` double DEFAULT NULL,
  `totalInterractionTime` int(11) DEFAULT NULL,
  `totalInterractions` int(11) DEFAULT NULL,
  `totalConversions` int(11) DEFAULT NULL,
  `clickThroughConv` int(11) DEFAULT NULL,
  `viewThroughConv` int(11) NOT NULL,
  `videoFirstQuatileCompletions` int(11) DEFAULT NULL,
  `videoThirdQuatileCompletions` int(11) DEFAULT NULL,
  `videoMidpoints` int(11) DEFAULT NULL,
  `videoCompletions` int(11) DEFAULT NULL,
  `videoPlays` int(11) DEFAULT NULL,
  `videoReplays` int(11) DEFAULT NULL,
  `videoViews` int(11) DEFAULT NULL,
  `videoInteractions` int(11) DEFAULT NULL,
  `expansions` int(11) DEFAULT NULL,
  `avViewableImpressions` int(11) NOT NULL,
  `avMeasurableImpressions` int(11) DEFAULT NULL,
  `dbmCost` decimal(10,2) NOT NULL,
  `dbmCostUsd` decimal(10,2) NOT NULL,
  `excludeCode` tinyint(1) DEFAULT '0',
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_dc_reports_data_dbm_campaignId` (`campaignId`),
  KEY `size` (`size`),
  KEY `idx_dc_reports_data_dbm_advertiserId` (`advertiserId`),
  KEY `idx_dc_reports_data_dbm_placementId` (`placementId`),
  KEY `idx_dc_reports_data_dbm_advertiserDbmId` (`advertiserDbmId`),
  KEY `idx_dc_reports_data_dbm_siteDbmId` (`siteDbmId`),
  KEY `idx_dc_reports_data_dbm_insertionOrderDbmId` (`insertionOrderDbmId`),
  KEY `idx_dc_reports_data_dbm_impressions` (`impressions`),
  KEY `idx_dc_reports_data_dbm_clicks` (`clicks`),
  KEY `idx_dc_reports_data_dbm_date` (`date`),
  KEY `excludeCode` (`excludeCode`),
  KEY `profileId` (`profileId`),
  KEY `accountId` (`accountId`)
) ENGINE=InnoDB AUTO_INCREMENT=164861352 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
