CREATE TABLE `dc_reports_data_placement_creative_url` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `placementId` int(11) NOT NULL,
  `creativeId` int(11) NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `siteId` int(11) NOT NULL,
  `adType` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `creativeType` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `clickThroughUrl` varchar(1024) COLLATE utf8_unicode_ci NOT NULL,
  `url_clean_id` int(10) unsigned DEFAULT NULL,
  `dynamicUniqueNumber` bigint(20) NOT NULL DEFAULT '0',
  `impressions` decimal(10,0) NOT NULL,
  `clicks` decimal(10,0) NOT NULL,
  `cost_share` decimal(15,5) NOT NULL,
  `track_click` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `placementId` (`placementId`),
  KEY `creativeId` (`creativeId`),
  KEY `advertiserId` (`advertiserId`) USING BTREE,
  KEY `url_clean_id` (`url_clean_id`) USING BTREE,
  KEY `campaignId` (`campaignId`) USING BTREE,
  KEY `siteId` (`siteId`) USING BTREE,
  KEY `dynamicUniqueNumber` (`dynamicUniqueNumber`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=280721920 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
