CREATE TABLE `dc_reports_data_floodlight_var` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `placementId` int(11) NOT NULL,
  `creativeId` int(11) NOT NULL,
  `siteId` int(11) NOT NULL,
  `size` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `creativeType` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `adType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `floodlight_config_id` int(11) NOT NULL,
  `activity_id` int(11) NOT NULL,
  `activity` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `activity_group_id` int(11) NOT NULL,
  `activity_group` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension1` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension2` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension3` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension4` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension5` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension6` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension7` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension8` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension9` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension10` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension11` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension12` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension13` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension14` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension15` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension16` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension17` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension18` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension19` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floodlightVariableDimension20` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `totalConversions` int(11) DEFAULT NULL,
  `clickThroughConv` int(11) DEFAULT NULL,
  `viewThroughConv` int(11) NOT NULL,
  `avViewableImpressions` int(11) NOT NULL,
  `avMeasurableImpressions` int(11) DEFAULT NULL,
  `excludeCode` tinyint(1) NOT NULL DEFAULT '0',
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_dc_reports_data_date` (`date`) USING BTREE,
  KEY `idx_dc_reports_data_campaignId` (`campaignId`) USING BTREE,
  KEY `idx_dc_reports_data_advertiserId` (`advertiserId`) USING BTREE,
  KEY `idx_dc_reports_data_placementId` (`placementId`) USING BTREE,
  KEY `idx_dc_reports_data_creativeId` (`creativeId`) USING BTREE,
  KEY `idx_dc_reports_data_siteId` (`siteId`) USING BTREE,
  KEY `floodlight_config_id` (`floodlight_config_id`) USING BTREE,
  KEY `activity_id` (`activity_id`) USING BTREE,
  KEY `activity_group_id` (`activity_group_id`) USING BTREE,
  KEY `idx_dc_reports_data_impressions` (`impressions`) USING BTREE,
  KEY `idx_dc_reports_data_clicks` (`clicks`) USING BTREE,
  KEY `excludeCode` (`excludeCode`) USING BTREE,
  KEY `size` (`size`) USING BTREE,
  KEY `profileId` (`profileId`) USING BTREE,
  KEY `accountId` (`accountId`) USING BTREE,
  KEY `floodlightVariableDimension1` (`floodlightVariableDimension1`) USING BTREE,
  KEY `floodlightVariableDimension2` (`floodlightVariableDimension2`) USING BTREE,
  KEY `floodlightVariableDimension3` (`floodlightVariableDimension3`) USING BTREE,
  KEY `floodlightVariableDimension4` (`floodlightVariableDimension4`) USING BTREE,
  KEY `floodlightVariableDimension5` (`floodlightVariableDimension5`) USING BTREE,
  KEY `floodlightVariableDimension6` (`floodlightVariableDimension6`) USING BTREE,
  KEY `floodlightVariableDimension7` (`floodlightVariableDimension7`) USING BTREE,
  KEY `floodlightVariableDimension8` (`floodlightVariableDimension8`) USING BTREE,
  KEY `floodlightVariableDimension9` (`floodlightVariableDimension9`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=124410704 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
