CREATE TABLE `dc_reports_data_invalid` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `siteId` int(11) NOT NULL,
  `placementId` int(11) NOT NULL,
  `impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `clickRate` double DEFAULT NULL,
  `totalConversions` int(11) DEFAULT NULL,
  `clickThroughConv` int(11) DEFAULT NULL,
  `viewThroughConv` int(11) NOT NULL,
  `avViewableImpressions` int(11) NOT NULL,
  `avMeasurableImpressions` int(11) DEFAULT NULL,
  `avEligibleImpressions` int(11) DEFAULT NULL,
  `general_invalid_traffic_clicks` int(11) DEFAULT NULL,
  `general_invalid_traffic_impressions` int(11) DEFAULT NULL,
  `invalid_clicks` int(11) DEFAULT NULL,
  `invalid_impressions` int(11) DEFAULT NULL,
  `invalid_active_view_eligible_impressions` int(11) DEFAULT NULL,
  `invalid_active_view_measurable_impressions` int(11) DEFAULT NULL,
  `invalid_active_view_viewable_impressions` int(11) DEFAULT NULL,
  `general_invalid_traffic_active_view_eligible_impressions` int(11) DEFAULT NULL,
  `general_invalid_traffic_active_view_measurable_impressions` int(11) DEFAULT NULL,
  `general_invalid_traffic_active_view_viewable_impressions` int(11) DEFAULT NULL,
  `general_invalid_traffic_begin_to_render_impressions` int(11) DEFAULT NULL,
  `general_invalid_traffic_tracked_ads` int(11) DEFAULT NULL,
  `invalid_begin_to_render_impressions` int(11) DEFAULT NULL,
  `invalid_tracked_ads` int(11) DEFAULT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_dc_reports_data_date` (`date`),
  KEY `idx_dc_reports_data_campaignId` (`campaignId`),
  KEY `idx_dc_reports_data_advertiserId` (`advertiserId`),
  KEY `idx_dc_reports_data_placementId` (`placementId`),
  KEY `idx_dc_reports_data_siteId` (`siteId`),
  KEY `idx_dc_reports_data_impressions` (`impressions`),
  KEY `idx_dc_reports_data_clicks` (`clicks`),
  KEY `profileId` (`profileId`),
  KEY `accountId` (`accountId`)
) ENGINE=InnoDB AUTO_INCREMENT=23066158 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
