CREATE TABLE `dc_reports_data_month` (
  `month` date NOT NULL,
  `dateMin` date NOT NULL,
  `dateMax` date NOT NULL,
  `dateTotal` int(11) NOT NULL,
  `accountId` int(10) unsigned NOT NULL,
  `profileId` int(10) unsigned NOT NULL,
  `advertiserId` bigint(20) NOT NULL,
  `campaignId` int(10) unsigned NOT NULL,
  `siteId` int(11) NOT NULL,
  `placementId` int(11) NOT NULL,
  `impressions` int(11) NOT NULL,
  `measurableImpressions` int(11) NOT NULL,
  `viewableImpressions` int(11) NOT NULL,
  `defaultImpressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  PRIMARY KEY (`month`,`accountId`,`profileId`,`advertiserId`,`campaignId`,`siteId`,`placementId`),
  KEY `month` (`month`),
  KEY `accountId` (`accountId`),
  KEY `profileId` (`profileId`),
  KEY `advertiserId` (`advertiserId`),
  KEY `campaignId` (`campaignId`),
  KEY `siteId` (`siteId`),
  KEY `placementId` (`placementId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
