CREATE TABLE `dc_reports_data_dynamic_old` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `campaignId` int(11) NOT NULL,
  `advertiserId` int(11) NOT NULL,
  `placementId` int(11) NOT NULL,
  `creativeId` int(11) NOT NULL,
  `siteId` int(11) NOT NULL,
  `size` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `creativeType` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `adType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dynamic_element` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dynamic_element_value` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dynamic_impressions` int(11) NOT NULL,
  `dynamic_clicks` int(11) NOT NULL,
  `dynamic_ctr` double NOT NULL,
  `dynamic_total_conversions` int(11) NOT NULL,
  `dynamic_ctr_conversions` int(11) NOT NULL,
  `dynamic_view_conversions` int(11) NOT NULL,
  `type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type_value1` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type_value2` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type_value3` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type_value4` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type_value5` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `campaignId` (`campaignId`),
  KEY `advertiserId` (`advertiserId`),
  KEY `placementId` (`placementId`),
  KEY `creativeId` (`creativeId`),
  KEY `siteId` (`siteId`),
  KEY `dynamic_element` (`dynamic_element`),
  KEY `type` (`type`)
) ENGINE=InnoDB AUTO_INCREMENT=58500 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
