CREATE TABLE `dc_reports_files` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `fileId` bigint(20) NOT NULL,
  `reportId` int(11) NOT NULL,
  `filename` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `localFilePath` longtext COLLATE utf8mb4_unicode_ci,
  `remoteFilePath` longtext COLLATE utf8mb4_unicode_ci,
  `format` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `startDate` date DEFAULT NULL,
  `endDate` date DEFAULT NULL,
  `isImported` tinyint(1) DEFAULT NULL,
  `isCostProcessed` tinyint(1) DEFAULT '0',
  `lastModifiedDate` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `accountId` int(10) unsigned DEFAULT NULL,
  `profileId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `profileId` (`profileId`),
  KEY `accountId` (`accountId`),
  KEY `fileId` (`fileId`),
  KEY `reportId` (`reportId`),
  KEY `isImported` (`isImported`)
) ENGINE=InnoDB AUTO_INCREMENT=259859 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
