CREATE TABLE `di_booking_placement_link` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sourceUuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bookingUniqueNumber` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `placementId` bigint(20) unsigned DEFAULT NULL,
  `placementUniqueNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tsfCurrentAccountId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isClickTracker` tinyint(1) NOT NULL DEFAULT '0',
  `placementDateStart` date DEFAULT NULL,
  `placementDateEnd` date DEFAULT NULL,
  `campaignId` bigint(20) unsigned DEFAULT NULL,
  `advertiserId` bigint(20) unsigned DEFAULT NULL,
  `siteId` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sourceModifiedAt` datetime DEFAULT NULL,
  `syncedAt` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_row` (`source`,`sourceUuid`),
  KEY `ix_placement` (`placementId`),
  KEY `ix_booking` (`bookingUniqueNumber`),
  KEY `ix_placement_unique` (`placementUniqueNumber`),
  KEY `ix_source_modified` (`source`,`sourceModifiedAt`)
) ENGINE=InnoDB AUTO_INCREMENT=131524 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
