CREATE TABLE `ds_bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdHost` datetime NOT NULL,
  `createdBy` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `modifiedHost` datetime NOT NULL,
  `modifiedBy` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bookingUniqueNumber` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dateInsertion` date NOT NULL,
  `fundamentalInvoiceOffice` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientAccountNumber` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mediaName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `publisherOffice` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dateEventEnd` date NOT NULL,
  `dateInsertionDeadline` date NOT NULL,
  `opportunity` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `comment` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `rateCard` decimal(15,5) DEFAULT NULL,
  `rateOffer` decimal(15,5) DEFAULT NULL,
  `impressions` int(11) NOT NULL,
  `rateOfferTotal` int(11) NOT NULL,
  `exchClientReportingCurrency` int(11) NOT NULL,
  `currencyBase` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `currencyMedia` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientReportingCurrency` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `costToClient` decimal(13,2) NOT NULL,
  `costToClientInClientReportingCurrency` decimal(13,2) NOT NULL,
  `costToClientInSystemBaseCurrency` decimal(13,2) NOT NULL,
  `budgetCode1` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `budgetCode2` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `budgetCodeYear` int(11) NOT NULL,
  `copyToRun` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `copyRan` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mediaType` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `region` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `size` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `voucherCopyCheck` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `voucherCopyPosition` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `resourceRequired` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `opportunityType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `costStructure` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_tsfCampaigns` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `syncedBooking` tinyint(1) DEFAULT NULL,
  `product` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `planUniqueNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_alert` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tsfSiteId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_tsfAssociatedChildBookings` text COLLATE utf8mb4_unicode_ci,
  `id_tsfParentBooking` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `audience` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `targeting` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assetClass` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managementStyle` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plan_product` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impressions_estimated` int(11) NOT NULL,
  `clientUuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `removed` tinyint(1) DEFAULT NULL,
  `budgetCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `budgetcodeName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `layer` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `excludeFromTrafficking` tinyint(1) NOT NULL,
  `agencyFeePercentage` decimal(10,5) DEFAULT '0.00000',
  `orderNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `costToTitleInSystemBaseCurrency` decimal(13,2) DEFAULT NULL,
  `costToTitle` decimal(13,2) DEFAULT NULL,
  `id_booking_credited` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ds_bookings_uuid_bookinguniquenumber_unique` (`uuid`,`bookingUniqueNumber`),
  UNIQUE KEY `bookingUniqueNumber` (`bookingUniqueNumber`),
  UNIQUE KEY `bookingUniqueNumber_2` (`bookingUniqueNumber`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `ds_bookings_uuid_index` (`uuid`),
  KEY `ds_bookings_bookinguniquenumber_index` (`bookingUniqueNumber`),
  KEY `idx_ds_bookings_dateInsertion` (`dateInsertion`),
  KEY `idx_ds_bookings_dateEventEnd` (`dateEventEnd`),
  KEY `idx_ds_bookings_impressions` (`impressions`),
  KEY `syncedBooking` (`syncedBooking`),
  KEY `id_tsfParentBooking` (`id_tsfParentBooking`),
  KEY `removed` (`removed`),
  KEY `fundamentalInvoiceOffice` (`fundamentalInvoiceOffice`),
  KEY `clientUuid` (`clientUuid`),
  KEY `orderNumber` (`orderNumber`)
) ENGINE=InnoDB AUTO_INCREMENT=58640383 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
