CREATE TABLE `ds_fm_dynamic_content_item` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dynamic_content_id` int(10) unsigned NOT NULL,
  `uuid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `uuid_dynamic_content` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `uuid_current_account` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `reporting_label` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `exit_url` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `active` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `default_field` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `value1` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value2` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value3` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value4` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value5` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value6` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value7` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value8` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value9` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value10` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value11` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value12` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value13` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value14` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value15` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value16` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value17` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value18` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value19` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value20` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value21` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value22` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value23` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value24` longtext COLLATE utf8_unicode_ci NOT NULL,
  `value25` longtext COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  `created_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `modified` datetime NOT NULL,
  `modified_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `item_serial_number` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuidUnique` (`uuid`),
  KEY `dynamic_content_id` (`dynamic_content_id`),
  KEY `uuid_dynamic_content` (`uuid_dynamic_content`),
  KEY `uuid_current_account` (`uuid_current_account`),
  KEY `reporting_label` (`reporting_label`),
  KEY `active` (`active`),
  KEY `default_field` (`default_field`),
  KEY `modified` (`modified`),
  KEY `item_serial_number` (`item_serial_number`)
) ENGINE=InnoDB AUTO_INCREMENT=4872904 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
