CREATE TABLE `ds_fm_campaigns` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaignName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_clients` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `associatedPlanNumber` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `atp_reference` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fundamental_invoice_office` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaignDateStart` date DEFAULT NULL,
  `campaignDateEnd` date DEFAULT NULL,
  `doubleClickAdvertiserId` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `doubleClick_CampaignId` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dcm_account_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dcm_profile_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `defaultLandingPageName` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `defaultLandingPageUrl` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `budget_allocation_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaign_name_budget_year` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaign_name_period_prefix` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaign_name_region` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaign_name_audience_focus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaign_name_campaign_element` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaign_name_client_name_short` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaign_name_elements_json` text COLLATE utf8mb4_unicode_ci,
  `readyToUpload` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sentForApprovalName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sentForApprovalEmail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sentForApprovalTimestamp` datetime DEFAULT NULL,
  `audit` mediumtext COLLATE utf8mb4_unicode_ci,
  `createdBy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdHost` datetime DEFAULT NULL,
  `modifiedBy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modifiedHost` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ds_fm_campaigns_uuid` (`uuid`),
  KEY `idx_ds_fm_campaigns_id_clients` (`id_clients`),
  KEY `idx_ds_fm_campaigns_advertiser` (`doubleClickAdvertiserId`)
) ENGINE=InnoDB AUTO_INCREMENT=54732 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
