CREATE TABLE `ds_fm_bookings_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bookingUniqueNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tsfCurrentAccountId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tsfCampaignsId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campaignId` int(10) unsigned DEFAULT NULL,
  `placementId` int(10) unsigned DEFAULT NULL,
  `placementSize` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `placementDateStart` date NOT NULL,
  `placementDateEnd` date NOT NULL,
  `impressions` bigint(20) unsigned DEFAULT NULL,
  `bookedQuantity` bigint(20) unsigned DEFAULT NULL,
  `bookedTotalCost` double DEFAULT NULL,
  `traffickingString` varchar(511) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pricingType` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managementStyle` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `costStructure` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assetClass` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `placementUniqueNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `placement_name_short` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tracker_data_selector` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdHost` datetime DEFAULT NULL,
  `modifiedHost` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ds_fm_bookings_data_id_unique` (`uuid`),
  UNIQUE KEY `placementUniqueNumber` (`placementUniqueNumber`),
  KEY `idx_ds_fm_bookings_data_bookingUniqueNumber` (`bookingUniqueNumber`),
  KEY `idx_ds_fm_bookings_data_campaignId` (`campaignId`),
  KEY `idx_ds_fm_bookings_data_placementId` (`placementId`),
  KEY `idx_ds_fm_bookings_data_bookedQuantity` (`bookedQuantity`),
  KEY `modifiedHost` (`modifiedHost`)
) ENGINE=InnoDB AUTO_INCREMENT=2300610 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
