CREATE TABLE `ds_fm_advertiser_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `advertiser_settings_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_quantity` int(11) DEFAULT NULL,
  `element_delineator` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `element_field_label_01` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_02` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_03` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_04` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_05` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_06` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_07` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_08` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_09` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_10` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_11` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_12` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_13` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_14` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_15` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_16` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_field_label_17` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_01` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_02` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_03` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_04` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_05` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_06` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_07` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_08` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_09` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_10` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_11` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_12` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_13` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_14` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_15` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_16` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_type_17` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `element_key_text_01_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_02_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_03_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_04_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_05_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_06_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_07_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_08_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_09_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_10_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_11_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_12_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_13_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_14_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_15_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_16_global` text COLLATE utf8mb4_unicode_ci,
  `element_key_text_17_global` text COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_01` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_02` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_03` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_04` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_05` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_06` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_07` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_08` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_09` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_10` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_11` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_12` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_13` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_14` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_15` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_16` longtext COLLATE utf8mb4_unicode_ci,
  `element_value_list_json_17` longtext COLLATE utf8mb4_unicode_ci,
  `text_string_global` text COLLATE utf8mb4_unicode_ci,
  `text_string_length_global` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `text_string_allowable_length` int(11) DEFAULT NULL,
  `text_string_case` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `text_string_blank_value_substitute_character` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `text_string_substitute_character_list_json` longtext COLLATE utf8mb4_unicode_ci,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_host` datetime DEFAULT NULL,
  `modified_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modified_host` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ds_fm_advertiser_settings_uuid` (`uuid`),
  KEY `idx_ds_fm_advertiser_settings_type` (`advertiser_settings_type`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
