CREATE TABLE `ds_fm_dynamic_content` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `uuid_current_account` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `booking_unique_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `filename` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label2` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label3` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label4` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label5` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label6` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label7` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label8` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label9` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label10` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label11` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label12` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label13` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label14` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label15` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label16` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label17` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label18` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label19` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label20` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label21` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label22` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label23` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label24` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label25` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  `created_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `modified` datetime NOT NULL,
  `modified_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuidUnique` (`uuid`),
  KEY `uuid_current_account` (`uuid_current_account`),
  KEY `booking_unique_number` (`booking_unique_number`),
  KEY `name` (`name`),
  KEY `filename` (`filename`),
  KEY `modified` (`modified`)
) ENGINE=InnoDB AUTO_INCREMENT=204413 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
