CREATE TABLE `ds_fm_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_host` datetime DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modified_host` datetime DEFAULT NULL,
  `modified_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `license_expiry_date` date DEFAULT NULL,
  `host_ip_address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `warning_message` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unique_user_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_name_personal_messages` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_alerts` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `office_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `username_logged_in` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `yes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hold` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `open_field` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deadline_window` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signature` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `red` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `green` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `blue` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_colour` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `management_view` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_capturer` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `total_dropbox` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `open_dropbox` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `languages` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoice_approval_entry_count` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_first` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_last` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_full` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_formal` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `initials` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `department` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `senior_management_team` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `job_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_start` date DEFAULT NULL,
  `date_end` date DEFAULT NULL,
  `extension_work` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `line_manager` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_line_manager` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_training_author` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employment_status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pword` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_job_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_line_manager` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_approval_override_manager` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `netsuite_department` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `email_address` (`email_address`)
) ENGINE=InnoDB AUTO_INCREMENT=10988440 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
