CREATE TABLE `ds_moat` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `impressions_analyzed` int(11) NOT NULL,
  `measurable_impressions` int(11) NOT NULL,
  `l_full_visibility_measurable` int(11) NOT NULL,
  `l_full_visibility_ots` int(11) NOT NULL,
  `l_full_visibility_ots_1_sec` int(11) NOT NULL,
  `in_view_impressions` int(11) NOT NULL,
  `dfp_ad_server_clicks` int(11) NOT NULL,
  `dfp_ad_server_click_through_rate` double DEFAULT NULL,
  `page_dwell_time` double DEFAULT NULL,
  `time_to_scroll` double DEFAULT NULL,
  `time_to_hover` double DEFAULT NULL,
  `universal_interaction_time` double DEFAULT NULL,
  `time_to_touch` double DEFAULT NULL,
  `active_exposure_time` double DEFAULT NULL,
  `total_ad_dwell_time` double DEFAULT NULL,
  `active_in_view_time` double DEFAULT NULL,
  `hovers_percent` double DEFAULT NULL,
  `clicks_percent` double DEFAULT NULL,
  `in_view_percent` double DEFAULT NULL,
  `time_to_scroll_percent` double DEFAULT NULL,
  `l_full_visibility_ots_percent` double DEFAULT NULL,
  `l_full_visibility_ots_1_sec_percent` double DEFAULT NULL,
  `universal_interactions_percent` double DEFAULT NULL,
  `attention_quality` double DEFAULT NULL,
  `universal_touch_percent` double DEFAULT NULL,
  `level1_id` int(11) NOT NULL,
  `level2_id` int(11) NOT NULL,
  `level3_id` int(11) NOT NULL,
  `level4_id` int(11) NOT NULL,
  `level1_label` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `level2_label` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `level3_label` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `level4_label` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `screenshot` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `screenshot_local` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `screenshot_signed` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_hovers` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_hovers_local` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_hovers_signed` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_interactions` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_interactions_local` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_interactions_signed` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_clicks` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_clicks_local` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heatmap_clicks_signed` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signed_date` date DEFAULT NULL,
  `moat_score` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ds_moat_id_unique` (`id`),
  KEY `idx_ds_moat_level1_id` (`level1_id`),
  KEY `idx_ds_moat_level2_id` (`level2_id`),
  KEY `idx_ds_moat_level3_id` (`level3_id`),
  KEY `idx_ds_moat_level4_id` (`level4_id`),
  KEY `idx_ds_moat_impressions_analyzed` (`impressions_analyzed`),
  KEY `date` (`date`)
) ENGINE=InnoDB AUTO_INCREMENT=1062003 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
