CREATE TABLE `fb_ad_creative` (
  `creative_id` bigint(20) unsigned NOT NULL,
  `account_id` bigint(20) unsigned NOT NULL,
  `actor_id` bigint(20) unsigned DEFAULT NULL,
  `body` longtext COLLATE utf8mb4_unicode_ci,
  `call_to_action_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `effective_authorization_category` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `effective_instagram_media_id` bigint(20) unsigned DEFAULT NULL,
  `effective_instagram_story_id` bigint(20) unsigned DEFAULT NULL,
  `effective_object_story_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instagram_actor_id` bigint(20) unsigned DEFAULT NULL,
  `instagram_permalink_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `object_story_spec` longtext COLLATE utf8mb4_unicode_ci,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `object_story_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `object_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `object_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `video_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`creative_id`),
  KEY `account_id` (`account_id`),
  KEY `object_type` (`object_type`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
