CREATE TABLE `fb_ad_set` (
  `ad_set_id` bigint(20) unsigned NOT NULL,
  `account_id` bigint(20) unsigned NOT NULL,
  `campaign_id` bigint(20) unsigned NOT NULL,
  `bid_strategy` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `budget_remaining` decimal(15,5) DEFAULT NULL,
  `configured_status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `daily_budget` decimal(15,5) DEFAULT NULL,
  `effective_status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lifetime_budget` decimal(15,5) DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `optimization_goal` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_adset_id` bigint(20) unsigned DEFAULT NULL,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`ad_set_id`),
  KEY `account_id` (`account_id`),
  KEY `status` (`status`),
  KEY `campaign_id` (`campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
