CREATE TABLE `fb_campaign` (
  `campaign_id` bigint(20) unsigned NOT NULL,
  `bid_strategy` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buying_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `configured_status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `effective_status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `account_id` bigint(20) unsigned NOT NULL,
  `ad_strategy_id` bigint(20) unsigned DEFAULT NULL,
  `budget_remaining` decimal(15,5) DEFAULT NULL,
  `daily_budget` decimal(15,5) DEFAULT NULL,
  `lifetime_budget` decimal(15,5) DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `objective` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `pacing_type` longtext COLLATE utf8mb4_unicode_ci,
  `source_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `spend_cap` decimal(15,5) DEFAULT NULL,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `topline_id` bigint(20) unsigned NOT NULL,
  `start_time` datetime DEFAULT NULL,
  `stop_time` datetime DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`campaign_id`),
  KEY `account_id` (`account_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
