CREATE TABLE `ga_cohort_channel` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `view_id` int(11) NOT NULL,
  `channel` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` date NOT NULL,
  `day0` int(11) NOT NULL DEFAULT '0',
  `day1` int(11) NOT NULL DEFAULT '0',
  `day2` int(11) NOT NULL DEFAULT '0',
  `day3` int(11) NOT NULL DEFAULT '0',
  `day4` int(11) NOT NULL DEFAULT '0',
  `day5` int(11) NOT NULL DEFAULT '0',
  `day6` int(11) NOT NULL DEFAULT '0',
  `day7` int(11) NOT NULL DEFAULT '0',
  `day8` int(11) NOT NULL DEFAULT '0',
  `day9` int(11) NOT NULL DEFAULT '0',
  `day10` int(11) NOT NULL DEFAULT '0',
  `day11` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`),
  KEY `view_id` (`view_id`),
  KEY `channel` (`channel`),
  KEY `date` (`date`)
) ENGINE=InnoDB AUTO_INCREMENT=698900464 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
