CREATE TABLE `ga_campaign_channel` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `view_id` int(11) NOT NULL,
  `channel` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `booking_unique_number` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `booking_placement_id` int(11) DEFAULT NULL,
  `date` date NOT NULL,
  `users` int(11) NOT NULL DEFAULT '0',
  `new_users` int(11) NOT NULL DEFAULT '0',
  `sessions` int(11) NOT NULL DEFAULT '0',
  `entrances` int(11) NOT NULL DEFAULT '0',
  `bounces` int(11) NOT NULL DEFAULT '0',
  `session_duration` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `unique_pageviews` int(11) NOT NULL DEFAULT '0',
  `time_on_page` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `pageviews` int(11) NOT NULL DEFAULT '0',
  `exits` int(11) NOT NULL DEFAULT '0',
  `booking_creative_id` int(11) DEFAULT NULL,
  `booking_line_item_id` bigint(20) DEFAULT NULL,
  `facebook_ad_id` bigint(20) unsigned DEFAULT NULL,
  `linkedin_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `twitter_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `dynamic_unique_number` int(10) unsigned DEFAULT NULL,
  `amx_line_item_id` bigint(20) unsigned DEFAULT NULL,
  `amx_auction_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linkedin_creative_id` bigint(20) unsigned DEFAULT NULL,
  `smart_placement_stream_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `channel` (`channel`),
  KEY `campaign` (`campaign`),
  KEY `booking_unique_number` (`booking_unique_number`),
  KEY `booking_placement_id` (`booking_placement_id`),
  KEY `account_id` (`account_id`),
  KEY `view_id` (`view_id`),
  KEY `date` (`date`),
  KEY `booking_creative_id` (`booking_creative_id`),
  KEY `booking_line_item_id` (`booking_line_item_id`),
  KEY `facebook_ad_id` (`facebook_ad_id`),
  KEY `linkedin_campaign_id` (`linkedin_campaign_id`),
  KEY `twitter_campaign_id` (`twitter_campaign_id`),
  KEY `dynamic_unique_number` (`dynamic_unique_number`),
  KEY `amx_line_item_id` (`amx_line_item_id`),
  KEY `amx_auction_id` (`amx_auction_id`),
  KEY `linkedin_creative_id` (`linkedin_creative_id`) USING BTREE,
  KEY `smart_placement_stream_id` (`smart_placement_stream_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4652306 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
