CREATE TABLE `ga_property` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `property_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `internal_web_property_id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `website_url` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `level` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `profile_count` int(11) NOT NULL,
  `industry_vertical` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `default_profile_id` int(11) NOT NULL,
  `data_retention_ttl` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `data_retention_reset_on_new_activity` tinyint(1) NOT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `google_created` datetime NOT NULL,
  `google_updated` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `property_id` (`property_id`),
  KEY `account_id` (`account_id`),
  KEY `internal_web_property_id` (`internal_web_property_id`),
  KEY `name` (`name`),
  KEY `status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=8503066 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
