CREATE TABLE `ga_view` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `view_id` int(11) NOT NULL,
  `internal_web_property_id` int(11) NOT NULL,
  `web_property_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `website_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `currency` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `timezone` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `google_created` datetime NOT NULL,
  `google_updated` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `report_run` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `utm_booking_ref` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'ga:adContent',
  PRIMARY KEY (`id`),
  UNIQUE KEY `view_id` (`view_id`),
  KEY `account_id` (`account_id`),
  KEY `name` (`name`),
  KEY `report_run` (`report_run`),
  KEY `status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=31641863 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
