CREATE TABLE `ga_v4_property` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `property_id` bigint(20) unsigned NOT NULL,
  `account_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `time_zone` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `currency_code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `service_level` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `property_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `industry_category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `google_created` datetime NOT NULL,
  `google_updated` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `report_run` tinyint(1) NOT NULL DEFAULT '1',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'live',
  `utm_booking_ref` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'sessionManualAdContent',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `property_id` (`property_id`),
  KEY `status` (`status`) USING BTREE,
  KEY `display_name` (`display_name`) USING BTREE,
  KEY `time_zone` (`time_zone`) USING BTREE,
  KEY `currency_code` (`currency_code`) USING BTREE,
  KEY `account_id` (`account_id`) USING BTREE,
  KEY `industry_category` (`industry_category`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2858933 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
