CREATE TABLE `ga_v4_report_booking` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` bigint(20) unsigned NOT NULL,
  `property_id` bigint(20) unsigned NOT NULL,
  `booking_unique_number` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `booking_placement_id` int(11) DEFAULT NULL,
  `date` date NOT NULL,
  `users` int(11) NOT NULL DEFAULT '0',
  `sessions` int(11) NOT NULL DEFAULT '0',
  `engaged_sessions` int(11) NOT NULL DEFAULT '0',
  `engagement_rate` decimal(10,6) NOT NULL DEFAULT '0.000000',
  `bounce_rate` decimal(10,6) NOT NULL DEFAULT '0.000000',
  `booking_creative_id` int(11) DEFAULT NULL,
  `booking_line_item_id` bigint(20) DEFAULT NULL,
  `facebook_ad_id` bigint(20) unsigned DEFAULT NULL,
  `linkedin_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `twitter_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `dynamic_unique_number` int(10) unsigned DEFAULT NULL,
  `amx_line_item_id` bigint(20) unsigned DEFAULT NULL,
  `amx_auction_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linkedin_creative_id` bigint(20) unsigned DEFAULT NULL,
  `smart_placement_stream_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `google_ads_ad_id` bigint(20) unsigned DEFAULT NULL,
  `google_ads_keyword` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `google_ads_placement_category_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alphix_ledger` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `google_ads_ad_group_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `booking_unique_number` (`booking_unique_number`) USING BTREE,
  KEY `booking_placement_id` (`booking_placement_id`) USING BTREE,
  KEY `account_id` (`account_id`) USING BTREE,
  KEY `property_id` (`property_id`) USING BTREE,
  KEY `date` (`date`) USING BTREE,
  KEY `booking_creative_id` (`booking_creative_id`) USING BTREE,
  KEY `booking_line_item_id` (`booking_line_item_id`) USING BTREE,
  KEY `facebook_ad_id` (`facebook_ad_id`) USING BTREE,
  KEY `linkedin_campaign_id` (`linkedin_campaign_id`) USING BTREE,
  KEY `twitter_campaign_id` (`twitter_campaign_id`) USING BTREE,
  KEY `dynamic_unique_number` (`dynamic_unique_number`) USING BTREE,
  KEY `amx_line_item_id` (`amx_line_item_id`) USING BTREE,
  KEY `amx_auction_id` (`amx_auction_id`) USING BTREE,
  KEY `linkedin_creative_id` (`linkedin_creative_id`) USING BTREE,
  KEY `smart_placement_stream_id` (`smart_placement_stream_id`) USING BTREE,
  KEY `test_google_ads_ad_id_IDX` (`google_ads_ad_id`) USING BTREE,
  KEY `test_google_ads_keyword_IDX` (`google_ads_keyword`) USING BTREE,
  KEY `test_google_ads_placement_category_id_IDX` (`google_ads_placement_category_id`) USING BTREE,
  KEY `test_alphix_ledger_IDX` (`alphix_ledger`) USING BTREE,
  KEY `test_google_ads_ad_group_id_IDX` (`google_ads_ad_group_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=264646 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
