CREATE TABLE `ip_bot_classification_history` (
  `id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `source` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `period_start_date` date NOT NULL,
  `period_end_date` date NOT NULL,
  `processing_date` date NOT NULL,
  `ip` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `country` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `total_agents` int(10) unsigned NOT NULL DEFAULT '0',
  `no_agents` int(10) unsigned NOT NULL DEFAULT '0',
  `linux_agents` int(10) unsigned NOT NULL DEFAULT '0',
  `linux_ratio` decimal(4,2) unsigned NOT NULL DEFAULT '0.00',
  `web_crawlers` int(10) unsigned NOT NULL DEFAULT '0',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `page_visits` int(10) unsigned NOT NULL DEFAULT '0',
  `first_seen` date NOT NULL,
  `last_seen` date NOT NULL,
  `active_days` int(10) unsigned NOT NULL DEFAULT '0',
  `high_active_days` int(10) unsigned NOT NULL DEFAULT '0',
  `high_activity_ratio` decimal(4,2) unsigned NOT NULL DEFAULT '0.00',
  `highest_hits` int(10) unsigned NOT NULL DEFAULT '0',
  `total_high_hits` int(10) unsigned NOT NULL DEFAULT '0',
  `consecutive_days_total` int(10) unsigned NOT NULL DEFAULT '0',
  `consecutive_periods` int(10) unsigned NOT NULL DEFAULT '0',
  `consecutive_period_longest` int(10) unsigned NOT NULL DEFAULT '0',
  `consecutive_days_volume` int(10) unsigned NOT NULL DEFAULT '0',
  `consecutive_days_high_volume` int(10) unsigned NOT NULL DEFAULT '0',
  `consecutive_days_high` int(10) unsigned NOT NULL DEFAULT '0',
  `consecutive_day_ratio` decimal(4,2) unsigned NOT NULL DEFAULT '0.00',
  `consecutive_hit_ratio` decimal(4,2) unsigned NOT NULL DEFAULT '0.00',
  `high_hit_hammering_ratio` decimal(4,2) unsigned NOT NULL DEFAULT '0.00',
  `high_hit_consecutive_ratio` decimal(4,2) unsigned NOT NULL DEFAULT '0.00',
  `classifier_linux_bot` tinyint(1) NOT NULL DEFAULT '0',
  `classifier_crawler` tinyint(1) NOT NULL DEFAULT '0',
  `classifier_hammering_bot` tinyint(1) NOT NULL DEFAULT '0',
  `classifier_continuous_pattern_bot` tinyint(1) NOT NULL DEFAULT '0',
  `bot` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ibch_unique_key` (`ip`,`period_start_date`,`period_end_date`),
  KEY `country` (`country`),
  KEY `period_start_date` (`period_start_date`),
  KEY `period_end_date` (`period_end_date`),
  KEY `processing_date` (`processing_date`),
  KEY `bot` (`bot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
