CREATE TABLE `ip_flow_business` (
  `businessId` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `businessName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `website` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `alternateDomains` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `registrationAuthority` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `registrationNumber` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `registrationYear` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `registrationDateOfCreation` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `employeeBandId` int(10) unsigned DEFAULT NULL,
  `employeeBand` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `turnoverAmount` decimal(25,5) DEFAULT NULL,
  `turnoverType` int(10) unsigned DEFAULT NULL,
  `turnoverBand` int(10) unsigned DEFAULT NULL,
  `turnoverBandDescription` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `turnoverCurrencySymbol` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `turnoverCurrencyName` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `turnoverIsoCurrencySymbol` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `accountsNextDue` date DEFAULT NULL,
  `previousBusinessNames` longtext COLLATE utf8_unicode_ci,
  `lastUpdate` datetime NOT NULL,
  PRIMARY KEY (`businessId`),
  KEY `lastUpdate` (`lastUpdate`),
  KEY `employeeBand` (`employeeBand`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
