CREATE TABLE `li_account` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `token_user_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `account_id` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `reference` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `test` tinyint(1) DEFAULT '0',
  `serving_status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `currency` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `notified_on_campaign_optimization` tinyint(1) DEFAULT '0',
  `notified_on_creative_approval` tinyint(1) DEFAULT '0',
  `notified_on_creative_rejection` tinyint(1) DEFAULT '0',
  `notified_on_end_of_campaign` tinyint(1) DEFAULT '0',
  `notified_on_new_features_enabled` tinyint(1) DEFAULT '0',
  `created` datetime DEFAULT NULL,
  `last_modified` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_account` (`account_id`),
  KEY `token_user_id` (`token_user_id`),
  KEY `reference` (`reference`),
  KEY `status` (`status`),
  KEY `last_modified` (`last_modified`)
) ENGINE=InnoDB AUTO_INCREMENT=1293523 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
