CREATE TABLE `li_campaign` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `token_user_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `campaign_id` int(10) unsigned NOT NULL,
  `campaign_group_id` int(10) unsigned NOT NULL,
  `account_id` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `serving_status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `run_schedule_start` datetime NOT NULL,
  `run_schedule_end` datetime DEFAULT NULL,
  `creative_selection` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `unit_cost` decimal(13,2) NOT NULL,
  `unit_cost_currency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `daily_budget` decimal(13,2) DEFAULT NULL,
  `daily_budget_currency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `total_budget` decimal(13,2) DEFAULT NULL,
  `total_budget_currency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cost_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `format` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `objective_type` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `audience_expansion_enabled` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `offsite_delivery_enabled` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `active_audience_count` bigint(20) DEFAULT NULL,
  `total_audience_count` bigint(20) DEFAULT NULL,
  `last_modified` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_campaign` (`campaign_id`),
  KEY `token_user_id` (`token_user_id`),
  KEY `campaign_group_id` (`campaign_group_id`),
  KEY `account_id` (`account_id`),
  KEY `status` (`status`),
  KEY `last_modified` (`last_modified`),
  KEY `objective_type` (`objective_type`)
) ENGINE=InnoDB AUTO_INCREMENT=3092207 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
