CREATE TABLE `li_creative` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `token_user_id` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `creative_id` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `campaign_id` int(10) unsigned NOT NULL,
  `account_id` int(10) unsigned NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `serving_status` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `reference` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `leadgen_call_to_action_destination` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `review_status` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `li_created_at` datetime DEFAULT NULL,
  `last_modified` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `variables` longtext COLLATE utf8mb4_unicode_520_ci,
  `apiRawResponse` mediumtext COLLATE utf8mb4_unicode_520_ci,
  `headline` varchar(1000) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `creativeText` mediumtext COLLATE utf8mb4_unicode_520_ci,
  `topicList` text COLLATE utf8mb4_unicode_520_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_creative` (`creative_id`),
  KEY `token_user_id` (`token_user_id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `account_id` (`account_id`),
  KEY `status` (`status`),
  KEY `last_modified` (`last_modified`),
  KEY `reference` (`reference`) USING BTREE,
  KEY `leadgen_call_to_action_destination` (`leadgen_call_to_action_destination`)
) ENGINE=InnoDB AUTO_INCREMENT=190157227 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
