CREATE TABLE `li_post` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `token_user_id` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_reference` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `author` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `is_dsc` tinyint(1) DEFAULT NULL,
  `dsc_ad_account` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `dsc_ad_type` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `dsc_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `dsc_status` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `commentary` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `content` longtext COLLATE utf8mb4_unicode_520_ci,
  `container` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `content_landing_page` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `content_call_to_action_label` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `distribution_feed` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `distribution_target_entities` longtext COLLATE utf8mb4_unicode_520_ci,
  `distribution_third_party` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `is_reshare_disabled_by_author` tinyint(1) DEFAULT NULL,
  `life_cycle_state` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `reshare_parent` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `reshare_root` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `visibility` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `last_fetched` datetime NOT NULL,
  `last_modified` datetime NOT NULL,
  `published_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `post_reference` (`post_reference`) USING BTREE,
  KEY `token_user_id` (`token_user_id`) USING BTREE,
  KEY `last_fetched` (`last_fetched`) USING BTREE,
  KEY `last_modified` (`last_modified`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1296389 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
