CREATE TABLE `li_report_creative` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `token_user_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `account_id` int(10) unsigned NOT NULL,
  `creative_id` int(10) unsigned NOT NULL,
  `date` date NOT NULL,
  `action_clicks` int(11) NOT NULL,
  `ad_unit_clicks` int(11) NOT NULL,
  `approximate_unique_impressions` int(10) unsigned NOT NULL,
  `card_clicks` int(11) NOT NULL,
  `card_impressions` int(11) NOT NULL,
  `clicks` int(11) NOT NULL,
  `comment_likes` int(11) NOT NULL,
  `comments` int(11) NOT NULL,
  `company_page_clicks` int(11) NOT NULL,
  `conversion_value_in_local_currency` decimal(13,2) NOT NULL,
  `cost_in_local_currency` decimal(13,2) NOT NULL,
  `cost_in_usd` decimal(13,2) NOT NULL,
  `download_clicks` int(10) unsigned NOT NULL,
  `external_website_conversions` int(11) NOT NULL,
  `external_website_post_click_conversions` int(11) NOT NULL,
  `external_website_post_view_conversions` int(11) NOT NULL,
  `follows` int(11) NOT NULL,
  `full_screen_plays` int(11) NOT NULL,
  `impressions` int(11) NOT NULL,
  `job_applications` int(10) unsigned NOT NULL,
  `job_apply_clicks` int(10) unsigned NOT NULL,
  `landing_page_clicks` int(11) NOT NULL,
  `lead_generation_mail_contact_info_shares` int(11) NOT NULL,
  `lead_generation_mail_interested_clicks` int(11) NOT NULL,
  `likes` int(11) NOT NULL,
  `one_click_lead_form_opens` int(11) NOT NULL,
  `one_click_leads` int(11) NOT NULL,
  `opens` int(11) NOT NULL,
  `other_engagements` int(11) NOT NULL,
  `registrations` int(11) NOT NULL,
  `sends` int(10) unsigned NOT NULL,
  `shares` int(11) NOT NULL,
  `text_url_clicks` int(11) NOT NULL,
  `total_engagements` int(11) NOT NULL,
  `video_completions` int(11) NOT NULL,
  `video_first_quartile_completions` int(11) NOT NULL,
  `video_midpoint_completions` int(11) NOT NULL,
  `video_starts` int(11) NOT NULL,
  `video_third_quartile_completions` int(11) NOT NULL,
  `video_views` int(11) NOT NULL,
  `viral_card_clicks` int(11) NOT NULL,
  `viral_card_impressions` int(11) NOT NULL,
  `viral_clicks` int(11) NOT NULL,
  `viral_comments` int(11) NOT NULL,
  `viral_company_page_clicks` int(11) NOT NULL,
  `viral_external_website_conversions` int(11) NOT NULL,
  `viral_external_website_post_click_conversions` int(11) NOT NULL,
  `viral_external_website_post_view_conversions` int(11) NOT NULL,
  `viral_follows` int(11) NOT NULL,
  `viral_full_screen_plays` int(11) NOT NULL,
  `viral_impressions` int(11) NOT NULL,
  `viral_landing_page_clicks` int(11) NOT NULL,
  `viral_likes` int(11) NOT NULL,
  `viral_one_click_lead_form_opens` int(11) NOT NULL,
  `viral_one_click_leads` int(11) NOT NULL,
  `viral_other_engagements` int(11) NOT NULL,
  `viral_shares` int(11) NOT NULL,
  `viral_total_engagements` int(11) NOT NULL,
  `viral_video_completions` int(11) NOT NULL,
  `viral_video_first_quartile_completions` int(11) NOT NULL,
  `viral_video_midpoint_completions` int(11) NOT NULL,
  `viral_video_starts` int(11) NOT NULL,
  `viral_video_third_quartile_completions` int(11) NOT NULL,
  `viral_video_views` int(11) NOT NULL,
  `costGbp` decimal(13,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_creative_date` (`creative_id`,`date`),
  KEY `token_user_id` (`token_user_id`),
  KEY `account_id` (`account_id`),
  KEY `creative_id` (`creative_id`),
  KEY `date` (`date`)
) ENGINE=InnoDB AUTO_INCREMENT=194054539 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
