CREATE TABLE `mux_view` (
  `id` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `view_start` datetime NOT NULL,
  `view_end` datetime NOT NULL,
  `fetched` datetime DEFAULT NULL,
  `asn` int(10) unsigned DEFAULT NULL,
  `asn_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `buffering_count` int(11) DEFAULT NULL,
  `buffering_duration` int(11) DEFAULT NULL,
  `buffering_rate` decimal(15,4) DEFAULT NULL,
  `cdn` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `continent_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `error_type_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `exit_before_video_start` tinyint(1) DEFAULT NULL,
  `experiment_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inserted_at` datetime DEFAULT NULL,
  `isp` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `latitude` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `longitude` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `metro` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mux_api_version` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mux_embed_version` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mux_viewer_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `page_load_time` int(11) DEFAULT NULL,
  `page_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `page_url` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL,
  `platform_description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `platform_summary` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `playback_score` decimal(15,4) DEFAULT NULL,
  `player_autoplay` tinyint(1) DEFAULT NULL,
  `player_error_code` int(11) DEFAULT NULL,
  `player_error_message` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_height` int(11) DEFAULT NULL,
  `player_instance_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_language` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_load_time` int(11) DEFAULT NULL,
  `player_mux_plugin_version` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_poster` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_preload` tinyint(1) DEFAULT NULL,
  `player_software` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_software_version` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_source_domain` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_source_duration` int(11) DEFAULT NULL,
  `player_source_height` int(11) DEFAULT NULL,
  `player_source_host_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_source_stream_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_source_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_source_url` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_source_width` int(11) DEFAULT NULL,
  `player_startup_time` int(11) DEFAULT NULL,
  `player_version` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `player_view_count` int(11) DEFAULT NULL,
  `player_width` int(11) DEFAULT NULL,
  `preroll_ad_asset_hostname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `preroll_ad_tag_hostname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `preroll_played` tinyint(1) DEFAULT NULL,
  `preroll_requested` tinyint(1) DEFAULT NULL,
  `property_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `quality_score` decimal(15,4) DEFAULT NULL,
  `rebuffer_percentage` decimal(15,4) DEFAULT NULL,
  `rebuffering_score` decimal(15,4) DEFAULT NULL,
  `region` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `requests_for_first_preroll` int(11) DEFAULT NULL,
  `session_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `short_time` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `startup_score` decimal(15,4) DEFAULT NULL,
  `time_to_first_frame` int(11) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `used_fullscreen` tinyint(1) DEFAULT NULL,
  `video_content_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_duration` int(11) DEFAULT NULL,
  `video_encoding_variant` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_language` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_producer` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_series` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_startup_preroll_load_time` int(11) DEFAULT NULL,
  `video_startup_preroll_request_time` int(11) DEFAULT NULL,
  `video_stream_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_variant_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `video_variant_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `view_average_request_latency` int(11) DEFAULT NULL,
  `view_average_request_throughput` int(11) DEFAULT NULL,
  `view_error_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `view_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `view_max_downscale_percentage` decimal(15,4) DEFAULT NULL,
  `view_max_request_latency` int(11) DEFAULT NULL,
  `view_max_upscale_percentage` decimal(15,4) DEFAULT NULL,
  `view_seek_count` int(11) DEFAULT NULL,
  `view_seek_duration` int(11) DEFAULT NULL,
  `view_total_content_playback_time` int(11) DEFAULT NULL,
  `view_total_downscaling` int(11) DEFAULT NULL,
  `view_total_upscaling` int(11) DEFAULT NULL,
  `viewer_application_engine` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_application_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_application_version` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_device_category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_device_manufacturer` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_device_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_experience_score` decimal(15,4) DEFAULT NULL,
  `viewer_os_architecture` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_os_family` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_os_version` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `viewer_user_agent` longtext COLLATE utf8_unicode_ci,
  `viewer_user_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `watch_time` int(11) DEFAULT NULL,
  `watched` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `view_start` (`view_start`),
  KEY `view_end` (`view_end`),
  KEY `fetched` (`fetched`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
