CREATE TABLE `piano_report` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `site` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `utm_content` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visit_bounce` tinyint(1) DEFAULT NULL,
  `m_visits` int(10) DEFAULT NULL,
  `m_unique_visitors` int(10) DEFAULT NULL,
  `m_page_loads` int(10) DEFAULT NULL,
  `m_events` int(10) DEFAULT NULL,
  `m_time_spent_per_visits` decimal(10,2) DEFAULT NULL,
  `date` date NOT NULL,
  `booking_unique_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `booking_placement_id` bigint(20) unsigned DEFAULT NULL,
  `booking_creative_id` bigint(20) unsigned DEFAULT NULL,
  `booking_line_item_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dynamic_unique_number` bigint(20) unsigned DEFAULT NULL,
  `fullTag` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `siteId` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amx_line_item_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amx_auction_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entrances` int(10) unsigned DEFAULT NULL,
  `bounces` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=17659 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
