CREATE TABLE `psychographix_shard_url` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `url` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL,
  `url_norm` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL,
  `url_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `shard_id` int(10) unsigned NOT NULL,
  `investing_knowledge` decimal(5,2) DEFAULT NULL,
  `investing_involvement` decimal(5,2) DEFAULT NULL,
  `risk_tolerance` decimal(5,2) DEFAULT NULL,
  `expert_reliance` decimal(5,2) DEFAULT NULL,
  `buy_and_hold` decimal(5,2) DEFAULT NULL,
  `investing_enjoyment` decimal(5,2) DEFAULT NULL,
  `financial_comfort` decimal(5,2) DEFAULT NULL,
  `analytical_approach` decimal(5,2) DEFAULT NULL,
  `passive_vs_active` decimal(5,2) DEFAULT NULL,
  `title` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `netloc` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `author` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `language` char(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'en',
  `published_on` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_url_hash` (`url_hash`),
  KEY `idx_shard_id` (`shard_id`),
  KEY `idx_netloc_published` (`netloc`,`published_on`)
) ENGINE=InnoDB AUTO_INCREMENT=34801097 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
