CREATE TABLE `psychographix_market_scenario` (
  `shard_id` int(10) unsigned NOT NULL,
  `financial_optimism` tinyint(3) unsigned DEFAULT NULL,
  `market_anxiety` tinyint(3) unsigned DEFAULT NULL,
  `greed_fomo` tinyint(3) unsigned DEFAULT NULL,
  `trust_in_institutions` tinyint(3) unsigned DEFAULT NULL,
  `loss_aversion_sensitivity` tinyint(3) unsigned DEFAULT NULL,
  `safety_seeking` tinyint(3) unsigned DEFAULT NULL,
  `innovation_excitement` tinyint(3) unsigned DEFAULT NULL,
  `skepticism_distrust` tinyint(3) unsigned DEFAULT NULL,
  `momentum_confidence` tinyint(3) unsigned DEFAULT NULL,
  `fear_of_recession` tinyint(3) unsigned DEFAULT NULL,
  `wealth_pride` tinyint(3) unsigned DEFAULT NULL,
  `resentment_exclusion` tinyint(3) unsigned DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `summary` text COLLATE utf8mb4_unicode_ci,
  `keywords` text COLLATE utf8mb4_unicode_ci,
  `url_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auction_count` decimal(15,2) DEFAULT NULL,
  `max_num_urls` int(11) DEFAULT NULL,
  `distinct_zip_count` int(11) DEFAULT NULL,
  `auction_weekly_pct_change` decimal(18,6) DEFAULT NULL,
  `processing_week` date NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`shard_id`,`processing_week`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
