CREATE TABLE `psychographix_zips` (
  `zipcode` char(5) COLLATE utf8mb4_unicode_ci NOT NULL,
  `county` text COLLATE utf8mb4_unicode_ci,
  `state` char(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `investing_knowledge` decimal(5,2) DEFAULT NULL,
  `investing_involvement` decimal(5,2) DEFAULT NULL,
  `risk_tolerance` decimal(5,2) DEFAULT NULL,
  `expert_reliance` decimal(5,2) DEFAULT NULL,
  `buy_and_hold` decimal(5,2) DEFAULT NULL,
  `investing_enjoyment` decimal(5,2) DEFAULT NULL,
  `financial_comfort` decimal(5,2) DEFAULT NULL,
  `analytical_approach` decimal(5,2) DEFAULT NULL,
  `passive_vs_active` decimal(5,2) DEFAULT NULL,
  `num_urls` int(10) unsigned NOT NULL DEFAULT '0',
  `auction_count` int(10) unsigned NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `processing_week` date NOT NULL,
  PRIMARY KEY (`zipcode`,`processing_week`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
