CREATE TABLE `tracker_page` (
  `id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` datetime NOT NULL,
  `country` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `page` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `delta_tag` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `ua` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `imported` datetime NOT NULL,
  `processed` datetime DEFAULT NULL,
  `processing_error` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `delta_tag_unique` int(10) unsigned DEFAULT NULL,
  `clean_page` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `referer` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `url_clean_id` int(10) unsigned DEFAULT NULL,
  `url_clean_processed` datetime DEFAULT NULL,
  `ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `domain_id` int(10) unsigned DEFAULT NULL,
  `delta_tag_unique_duplicate` tinyint(1) NOT NULL,
  `delta_tag_cm_placement_id` int(11) NOT NULL,
  `delta_tag_cm_creative_id` int(11) NOT NULL,
  `delta_tag_ca` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `channel` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `channel_processed` datetime DEFAULT NULL,
  `delta_tag_bm_line_item_id` bigint(20) DEFAULT NULL,
  `facebook_ad_id` bigint(20) unsigned DEFAULT NULL,
  `linkedin_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `twitter_campaign_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `country` (`country`),
  KEY `delta_tag` (`delta_tag`),
  KEY `ua` (`ua`),
  KEY `timestamp` (`timestamp`),
  KEY `processed` (`processed`),
  KEY `type` (`type`),
  KEY `delta_tag_unique` (`delta_tag_unique`),
  KEY `clean_page` (`clean_page`),
  KEY `url_clean_id` (`url_clean_id`),
  KEY `url_clean_processed` (`url_clean_processed`),
  KEY `domain_id` (`domain_id`),
  KEY `delta_tag_unique_duplicate` (`delta_tag_unique_duplicate`),
  KEY `delta_tag_cm_placement_id` (`delta_tag_cm_placement_id`),
  KEY `delta_tag_cm_creative_id` (`delta_tag_cm_creative_id`),
  KEY `delta_tag_ca` (`delta_tag_ca`),
  KEY `channel` (`channel`),
  KEY `channel_processed` (`channel_processed`),
  KEY `ip` (`ip`),
  KEY `delta_tag_bm_line_item_id` (`delta_tag_bm_line_item_id`),
  KEY `facebook_ad_id` (`facebook_ad_id`),
  KEY `linkedin_campaign_id` (`linkedin_campaign_id`),
  KEY `twitter_campaign_id` (`twitter_campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
