CREATE TABLE `tracker_impression` (
  `id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `country` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `delta_tag` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `ua` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` datetime NOT NULL,
  `imported` datetime NOT NULL,
  `processed` datetime DEFAULT NULL,
  `processing_error` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `delta_tag_ca` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `delta_tag_cm_placement_id` int(11) NOT NULL,
  `delta_tag_cm_creative_id` int(11) NOT NULL,
  `delta_tag_bm_line_item_id` bigint(20) DEFAULT NULL,
  `facebook_ad_id` bigint(20) unsigned DEFAULT NULL,
  `linkedin_campaign_id` bigint(20) unsigned DEFAULT NULL,
  `twitter_campaign_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `country` (`country`),
  KEY `delta_tag` (`delta_tag`),
  KEY `ua` (`ua`),
  KEY `timestamp` (`timestamp`),
  KEY `processed` (`processed`),
  KEY `type` (`type`),
  KEY `delta_tag_ca` (`delta_tag_ca`),
  KEY `delta_tag_cm_placement_id` (`delta_tag_cm_placement_id`),
  KEY `delta_tag_cm_creative_id` (`delta_tag_cm_creative_id`),
  KEY `delta_tag_bm_line_item_id` (`delta_tag_bm_line_item_id`),
  KEY `facebook_ad_id` (`facebook_ad_id`),
  KEY `linkedin_campaign_id` (`linkedin_campaign_id`),
  KEY `twitter_campaign_id` (`twitter_campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
